//! Bounded AOT tool invocation and strict producer-manifest validation.

use std::fs::{self, File};
use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

use ryft_core::kernels::{KernelCompilationError, KernelCompiler, KernelSchedule, NoKernelExtension, VerifiedKernel};
use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::kernels::cutile::lowering;
use crate::kernels::cutile::{
    COMPILER_SCHEMA_VERSION, CUDA_TILE_VERSION, CompiledKernel, Configuration, Error, NVCC_VERSION, NVVM_VERSION,
    Options, Parameter, TILEIRAS_VERSION, Target, Versions,
};

/// Compiler installation and optional cancellation signal. Neither owns any CUDA runtime resource.
#[derive(Clone, Debug)]
pub struct Compiler {
    /// Explicit Python interpreter path; no implicit environment or compiler selection.
    python: PathBuf,
    /// Caller-owned cancellation state, observed during each child invocation.
    cancellation: Arc<AtomicBool>,
}

/// Exact request generated by the trusted source lowering.
#[derive(Serialize)]
struct Request<'a> {
    /// Adapter contract schema.
    schema: u32,
    /// Actual admitted producer installation.
    versions: &'a Versions,
    /// Exact requested native architecture.
    target: String,
    /// Stable generated entry symbol.
    symbol: &'static str,
    /// Explicit canonical array constraints.
    parameters: &'a [Parameter],
    /// Physical tile grid.
    grid: [u32; 3],
    /// Native compiler deadline.
    compiler_timeout_seconds: f64,
    /// Maximum cubin size before either process reads it into memory.
    maximum_artifact_bytes: usize,
    /// Exact canonical body identity.
    semantic_key: String,
    /// Producer identity established before invocation.
    configuration_key: Vec<u8>,
}

impl Compiler {
    /// Selects an explicit Python installation. Constructing a compiler does not start Python or load CUDA.
    pub fn new(python: PathBuf) -> Self {
        Self { python, cancellation: Arc::new(AtomicBool::new(false)) }
    }

    /// Returns the configured Python executable path.
    pub fn python(&self) -> &Path {
        &self.python
    }

    /// Uses a caller-owned signal to cancel compilation, including the native compiler process group.
    /// Cancellation affects control flow only and never changes semantic or cache identity.
    pub fn with_cancellation(mut self, cancellation: Arc<AtomicBool>) -> Self {
        self.cancellation = cancellation;
        self
    }

    /// Checks the actual installed packages under the same bounded process policy as compilation.
    fn versions(&self, options: &Options) -> Result<Versions, Error> {
        let directory = tempfile::tempdir()?;
        fs::write(directory.path().join("export.py"), include_str!("export.py"))?;
        let (stdout, _) = self.run(directory.path(), &["export.py", "probe"], options)?;
        let response: serde_json::Value = serde_json::from_str(stdout.trim())?;
        if let Some(message) = response.get("missing").and_then(serde_json::Value::as_str) {
            return Err(Error::MissingDependency { message: message.to_owned() });
        }
        let versions: Versions = serde_json::from_value(response)?;
        if versions.cuda_tile != CUDA_TILE_VERSION
            || versions.tileiras != TILEIRAS_VERSION
            || versions.nvcc != NVCC_VERSION
            || versions.nvvm != NVVM_VERSION
            || versions.binary_version != TILEIRAS_VERSION
        {
            return Err(Error::Incompatible {
                message: format!(
                    "requires `cuda-tile=={CUDA_TILE_VERSION}`, `tileiras=={TILEIRAS_VERSION}`, `nvcc=={NVCC_VERSION}`, `nvvm=={NVVM_VERSION}` and executable `{TILEIRAS_VERSION}`, found `{versions:?}`",
                ),
            });
        }
        Ok(versions)
    }

    /// Encodes semantic compiler identity, excluding deadlines and cancellation policy.
    fn key(&self, target: &Target, schedule: &KernelSchedule) -> Result<Vec<u8>, Error> {
        if !self.python.is_absolute() {
            return Err(Error::Invalid { message: "Python executable must be an absolute path".into() });
        }
        Target::new(target.compute_capability().0, target.compute_capability().1)?;
        Ok(serde_json::to_vec(&Configuration {
            schema: COMPILER_SCHEMA_VERSION,
            cuda_tile: CUDA_TILE_VERSION.into(),
            tileiras: TILEIRAS_VERSION.into(),
            nvcc: NVCC_VERSION.into(),
            nvvm: NVVM_VERSION.into(),
            target: target.clone(),
            python: self.python.clone(),
            pipeline_stages: schedule.pipeline_stages().map(|value| value.get()),
            buffering_depth: schedule.buffering_depth().map(|value| value.get()),
            maximum_scratch_bytes: schedule.maximum_scratch_bytes(),
            worker_sha256: format!("{:x}", Sha256::digest(include_bytes!("export.py"))),
        })?)
    }

    /// Runs one isolated process group with bounded diagnostic capture and no pipe-draining deadlock.
    #[cfg(unix)]
    fn run(&self, directory: &Path, arguments: &[&str], options: &Options) -> Result<(String, String), Error> {
        use std::os::unix::process::CommandExt;

        if self.cancellation.load(Ordering::Acquire) {
            return Err(Error::Tool {
                reason: "cancelled before launch".into(),
                stdout: String::new(),
                stderr: String::new(),
            });
        }
        let stdout_path = directory.join("stdout.log");
        let stderr_path = directory.join("stderr.log");
        let mut command = Command::new(&self.python);
        command
            .args(arguments)
            .current_dir(directory)
            .env("PYTHONUNBUFFERED", "1")
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .stdin(Stdio::null())
            .stdout(File::create(&stdout_path)?)
            .stderr(File::create(&stderr_path)?)
            .process_group(0);
        let mut child = command.spawn().map_err(|source| Error::Unavailable { path: self.python.clone(), source })?;
        let start = Instant::now();
        let outcome = loop {
            match child.try_wait() {
                Ok(Some(status)) => break Ok(status),
                Err(error) => break Err(format!("failed while observing child: {error}")),
                Ok(None) => {}
            }
            let reason = if self.cancellation.load(Ordering::Acquire) {
                Some("cancelled".to_owned())
            } else if start.elapsed() >= options.process_timeout() {
                Some("timed out".to_owned())
            } else {
                match (fs::metadata(&stdout_path), fs::metadata(&stderr_path)) {
                    (Ok(stdout), Ok(stderr))
                        if stdout.len().max(stderr.len()) > options.maximum_diagnostic_bytes() as u64 =>
                    {
                        Some("exceeded the diagnostic capture limit".to_owned())
                    }
                    (Err(error), _) | (_, Err(error)) => Some(format!("failed to inspect diagnostic files: {error}")),
                    _ => None,
                }
            };
            if let Some(reason) = reason {
                break Err(reason);
            }
            std::thread::sleep(Duration::from_millis(10));
        };
        // Native compilers can outlive a Python failure. Always terminate the isolated process group, including on
        // successful Python exit; this cannot affect callers because process_group(0) created a fresh group.
        unsafe extern "C" {
            fn kill(process: i32, signal: i32) -> i32;
        }
        // SAFETY: negative child PID names only the new process group; SIGKILL has no pointer arguments.
        let result = unsafe { kill(-(child.id() as i32), 9) };
        if result != 0 {
            let error = std::io::Error::last_os_error();
            if error.raw_os_error() != Some(3) {
                return Err(Error::Io(error));
            }
        }
        child.wait()?;
        let read = |path: &Path| -> Result<String, Error> {
            let mut bytes = Vec::new();
            File::open(path)?.take(options.maximum_diagnostic_bytes() as u64).read_to_end(&mut bytes)?;
            Ok(String::from_utf8_lossy(&bytes).into_owned())
        };
        let stdout = read(&stdout_path)?;
        let stderr = read(&stderr_path)?;
        if fs::metadata(&stdout_path)?.len().max(fs::metadata(&stderr_path)?.len())
            > options.maximum_diagnostic_bytes() as u64
        {
            return Err(Error::Tool { reason: "exceeded the diagnostic capture limit".into(), stdout, stderr });
        }
        match outcome {
            Ok(status) if status.success() => Ok((stdout, stderr)),
            Ok(status) => Err(Error::Tool { reason: format!("exited with `{status}`"), stdout, stderr }),
            Err(reason) => Err(Error::Tool { reason, stdout, stderr }),
        }
    }

    /// The pinned build-time tool currently supports Unix process-group cancellation.
    #[cfg(not(unix))]
    fn run(&self, _directory: &Path, _arguments: &[&str], _options: &Options) -> Result<(String, String), Error> {
        Err(Error::Incompatible { message: "compiler process isolation requires a Unix host".into() })
    }
}

impl KernelCompiler for Compiler {
    type Target = Target;
    type Options = Options;
    type Output = CompiledKernel;
    type Error = Error;

    fn admit(
        &self,
        kernel: &VerifiedKernel<'_, NoKernelExtension>,
        target: &Target,
        options: &Options,
        schedule: &KernelSchedule,
    ) -> Result<(), KernelCompilationError<Error>> {
        Target::new(target.compute_capability().0, target.compute_capability().1).map_err(classify)?;
        lowering::lower(kernel, options, schedule).map_err(classify)?;
        self.versions(options).map_err(classify)?;
        Ok(())
    }

    fn configuration_key(
        &self,
        target: &Target,
        _options: &Options,
        schedule: &KernelSchedule,
    ) -> Result<Vec<u8>, KernelCompilationError<Error>> {
        self.key(target, schedule).map_err(classify)
    }

    fn compile(
        &self,
        kernel: &VerifiedKernel<'_, NoKernelExtension>,
        target: &Target,
        options: &Options,
        schedule: &KernelSchedule,
    ) -> Result<CompiledKernel, KernelCompilationError<Error>> {
        let source = lowering::lower(kernel, options, schedule).map_err(classify)?;
        let versions = self.versions(options).map_err(classify)?;
        let configuration_key = self.key(target, schedule).map_err(classify)?;
        let directory = tempfile::tempdir().map_err(Error::from).map_err(classify)?;
        let request = Request {
            schema: COMPILER_SCHEMA_VERSION,
            versions: &versions,
            target: target.architecture(),
            symbol: "ryft_cutile_kernel",
            parameters: &source.parameters,
            grid: source.grid,
            compiler_timeout_seconds: options.compiler_timeout().as_secs_f64(),
            maximum_artifact_bytes: options.maximum_artifact_bytes(),
            semantic_key: kernel.definition().semantic_key().map_err(Error::from).map_err(classify)?,
            configuration_key: configuration_key.clone(),
        };
        let execute = || -> Result<CompiledKernel, Error> {
            fs::write(directory.path().join("kernel.py"), &source.code)?;
            fs::write(directory.path().join("export.py"), include_str!("export.py"))?;
            fs::write(directory.path().join("request.json"), serde_json::to_vec(&request)?)?;
            let (stdout, stderr) = self.run(directory.path(), &["export.py", "request.json"], options)?;
            let artifact_path = directory.path().join("kernel.cubin");
            if fs::metadata(&artifact_path)?.len() > options.maximum_artifact_bytes() as u64 {
                return Err(Error::Artifact { message: "cubin exceeds the artifact size limit".into() });
            }
            let manifest_path = directory.path().join("manifest.json");
            if fs::metadata(&manifest_path)?.len() > options.maximum_diagnostic_bytes() as u64 {
                return Err(Error::Artifact { message: "manifest exceeds the size limit".into() });
            }
            let mut output =
                CompiledKernel::from_manifest(kernel, &fs::read(manifest_path)?, fs::read(artifact_path)?)?;
            if output.configuration_key() != configuration_key {
                return Err(Error::Artifact { message: "manifest changed compiler identity".into() });
            }
            output.diagnostics = format!("stdout:\n{stdout}\nstderr:\n{stderr}");
            Ok(output)
        };
        execute().map_err(classify)
    }
}

/// Retains canonical compiler error categories while preserving tool-specific diagnostics.
fn classify(error: Error) -> KernelCompilationError<Error> {
    match error {
        Error::Unsupported { operation, reason } => KernelCompilationError::Unsupported {
            owner: "ryft_cuda::kernels::cutile".into(),
            operation,
            requested: reason,
            capability: "cuTile source lowering".into(),
        },
        Error::Unavailable { path, source } => {
            KernelCompilationError::Unavailable { message: format!("`{}`: {source}", path.display()) }
        }
        Error::Incompatible { message } => KernelCompilationError::Incompatible { message },
        error => KernelCompilationError::Compiler(error),
    }
}

#[cfg(all(test, unix))]
mod tests {
    use pretty_assertions::assert_eq;

    use super::*;

    /// Uses a system shell only as a deterministic subprocess fixture; these tests never import cuTile.
    fn fixture() -> (Compiler, tempfile::TempDir) {
        (Compiler::new(PathBuf::from("/bin/sh")), tempfile::tempdir().unwrap())
    }

    #[test]
    fn test_compiler_configuration_key() {
        let compiler = Compiler::new("/missing/python".into());
        let target = Target::new(12, 1).unwrap();
        let schedule = KernelSchedule::default();
        let key = compiler.configuration_key(&target, &Options::default(), &schedule).unwrap();
        let short = Options::default().with_timeouts(Duration::from_millis(1), Duration::from_millis(2)).unwrap();
        assert_eq!(compiler.configuration_key(&target, &short, &schedule).unwrap(), key);
        assert_ne!(compiler.configuration_key(&Target::new(12, 0).unwrap(), &short, &schedule).unwrap(), key);
        assert_ne!(
            Compiler::new("/different/python".into()).configuration_key(&target, &short, &schedule).unwrap(),
            key
        );
    }

    #[test]
    fn test_compiler_run() {
        let (compiler, directory) = fixture();
        assert_eq!(
            compiler
                .run(directory.path(), &["-c", "printf stdout; printf stderr >&2"], &Options::default())
                .unwrap(),
            ("stdout".into(), "stderr".into())
        );
        let error = compiler
            .run(directory.path(), &["-c", "printf partial; printf diagnostic >&2; exit 7"], &Options::default())
            .unwrap_err();
        match error {
            Error::Tool { reason, stdout, stderr } => {
                assert!(reason.contains("7"));
                assert_eq!(stdout, "partial");
                assert_eq!(stderr, "diagnostic");
            }
            error => panic!("unexpected error: {error}"),
        }
        // A failed invocation retains no state capable of poisoning an independent successful invocation.
        assert_eq!(
            compiler.run(directory.path(), &["-c", "printf recovered"], &Options::default()).unwrap(),
            ("recovered".into(), String::new())
        );
    }

    #[test]
    fn test_compiler_run_missing_tool() {
        let directory = tempfile::tempdir().unwrap();
        let compiler = Compiler::new(directory.path().join("missing"));
        assert!(matches!(compiler.run(directory.path(), &[], &Options::default()), Err(Error::Unavailable { .. })));
    }

    #[test]
    fn test_compiler_run_timeout() {
        let (compiler, directory) = fixture();
        let options = Options::default().with_timeouts(Duration::from_millis(20), Duration::from_millis(100)).unwrap();
        let error = compiler
            .run(directory.path(), &["-c", "printf partial; printf failure >&2; sleep 30"], &options)
            .unwrap_err();
        match error {
            Error::Tool { reason, stdout, stderr } => {
                assert_eq!(reason, "timed out");
                assert_eq!(stdout, "partial");
                assert_eq!(stderr, "failure");
            }
            error => panic!("unexpected error: {error}"),
        }
    }

    #[test]
    fn test_compiler_run_cancellation() {
        let (compiler, directory) = fixture();
        let cancellation = Arc::new(AtomicBool::new(true));
        let compiler = compiler.with_cancellation(cancellation.clone());
        let error = compiler.run(directory.path(), &["-c", "exit 99"], &Options::default()).unwrap_err();
        assert!(matches!(error, Error::Tool { reason, .. } if reason == "cancelled before launch"));
        cancellation.store(false, Ordering::Release);
        let signal = cancellation.clone();
        let ready = directory.path().join("ready");
        let thread = std::thread::spawn(move || {
            let deadline = Instant::now() + Duration::from_secs(2);
            while !ready.exists() && Instant::now() < deadline {
                std::thread::sleep(Duration::from_millis(5));
            }
            assert!(ready.exists());
            signal.store(true, Ordering::Release);
        });
        let error = compiler
            .run(directory.path(), &["-c", "printf started; touch ready; sleep 30"], &Options::default())
            .unwrap_err();
        thread.join().unwrap();
        assert!(matches!(error, Error::Tool { reason, stdout, .. } if reason == "cancelled" && stdout == "started"));
    }
    #[test]
    fn test_compiler_versions() {
        use std::os::unix::fs::PermissionsExt;
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("python");
        let compiler = Compiler::new(path.clone());
        for (response, category) in [
            (
                format!(r#"{{"cuda_tile":"{CUDA_TILE_VERSION}","tileiras":"{TILEIRAS_VERSION}","nvcc":"13.3.73","nvvm":"13.3.73","binary_version":"13.3.36","python":"3.12.3"}}"#),
                "valid",
            ),
            (r#"{"cuda_tile":"1.0.0","tileiras":"13.3.36","nvcc":"13.3.73","nvvm":"13.3.73","binary_version":"13.3.36","python":"3.12.3"}"#.into(), "incompatible"),
            (r#"{"missing":"cuda-tile"}"#.into(), "missing"),
        ] {
            fs::write(&path, format!("#!/bin/sh\nprintf '%s' '{response}'\n")).unwrap();
            fs::set_permissions(&path, fs::Permissions::from_mode(0o700)).unwrap();
            match category {
                "valid" => assert_eq!(compiler.versions(&Options::default()).unwrap().python, "3.12.3"),
                "incompatible" => {
                    assert!(matches!(compiler.versions(&Options::default()), Err(Error::Incompatible { .. })))
                }
                _ => assert!(matches!(compiler.versions(&Options::default()), Err(Error::MissingDependency { .. }))),
            }
        }
    }

    #[test]
    fn test_compiler_compile() {
        use std::os::unix::fs::PermissionsExt;
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("python");
        let compiler = Compiler::new(path.clone());
        let target = Target::new(12, 1).unwrap();
        let schedule = KernelSchedule::default();
        let definition = crate::kernels::cutile::tests::definition(false);
        let kernel = VerifiedKernel::new(&definition, 1).unwrap();
        let cubin = crate::kernels::cutile::tests::cubin();
        let mut manifest = crate::kernels::cutile::tests::manifest(&kernel, &cubin);
        manifest.configuration_key = compiler.key(&target, &schedule).unwrap();
        fs::write(directory.path().join("fixture.cubin"), &cubin).unwrap();
        fs::write(directory.path().join("fixture.json"), serde_json::to_vec(&manifest).unwrap()).unwrap();
        // The fake tool only transports independent fixture metadata; it does not synthesize the decoder's result.
        let fixture = directory.path().to_str().unwrap().replace('\'', "'\"'\"'");
        fs::write(
            &path,
            format!(
                r#"#!/bin/sh
if [ "$2" = probe ]; then
  printf '%s' '{{"cuda_tile":"{CUDA_TILE_VERSION}","tileiras":"{TILEIRAS_VERSION}","nvcc":"13.3.73","nvvm":"13.3.73","binary_version":"13.3.36","python":"3.12.3"}}'
else
  cp '{fixture}/fixture.cubin' kernel.cubin
  cp '{fixture}/fixture.json' manifest.json
  printf 'compiled fixture'
fi
"#
            ),
        )
        .unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o700)).unwrap();
        let output = kernel.compile(&compiler, &target, &Options::default(), &schedule).unwrap();
        assert_eq!(output.artifact().bytes(), cubin);
        assert_eq!(
            output.arguments(),
            &[
                crate::kernels::cutile::Argument::Array(0),
                crate::kernels::cutile::Argument::I32(2),
                crate::kernels::cutile::Argument::I32(3),
                crate::kernels::cutile::Argument::I32(3),
                crate::kernels::cutile::Argument::I32(1)
            ]
        );
        assert_eq!(output.semantic_key(), definition.semantic_key().unwrap());
        assert_eq!(output.diagnostics(), "stdout:\ncompiled fixture\nstderr:\n");
    }
}
