//! Contains the [`CumulativeSumOperation`], the prefix-sum member of the cumulative family, together with the
//! [`CumulativeSum`] staging capability and the member's interpretation, partial-evaluation, batching, forward-mode
//! differentiation, and transposition rules.
//!
//! This is the family's one linear member, so it is written out by hand instead of being generated by
//! `define_cumulative_operation!`: it owns a real
//! transposition rule and a forward mode that rides the tangent through the same primitive.

// TODO(eaplatanios): Review this module.

use std::fmt::Display;

use crate::arrays::{ArrayBatch, ArrayBatching, ArrayType, DataType, RaggedArrayBatchingPolicy, RaggedMaskIdentity};
use crate::batching::{
    BatchAxis, BatchableOperation, BatchedOutputs, BatchingContext, BatchingDriver, BatchingError,
    InterpretableBatchableOperation,
};
use crate::contexts::{Context, Domain};
use crate::differentiation::{
    DifferentiableOperation, DifferentiableType, DifferentiationDriver, DifferentiationDual, DifferentiationError,
    TransposableOperation, TranspositionDriver,
};
use crate::interpretation::{InterpretableOperation, InterpretationDriver};
use crate::macros::check_count;
use crate::operations::cumulative::{cumulative_abstract, lift_cumulative_axis};
use crate::partial::{PartialValue, PartiallyEvaluatableOperation};
use crate::programs::{
    MaybeZero, Operation, OperationFormatter, ProgramError, RegionInterface, TypeError, Typed, Value,
};
use crate::tracing::{Tracer, TracingContext};

/// Canonical name of the [`CumulativeSumOperation`].
pub const CUMULATIVE_SUM_OPERATION_NAME: &str = "cumulative_sum";

/// Primitive representing one inclusive prefix sum along a single array axis.
///
/// Output element `i` along [`axis`](Self::axis) holds the sum of input elements `0..=i`, or the sum of elements
/// `i..` when [`reverse`](Self::reverse) is set. The output type is the input type, so a cumulative sum is a
/// shape-preserving unary primitive.
///
/// The identity of the combining operator is zero, which is what a batching rule writes over the padding of a
/// bounded ragged scanned axis so that padded positions cannot contribute to a live prefix.
///
/// `reverse` belongs to the payload rather than being spelled by the caller as a pair of reversals precisely
/// because it makes the primitive closed under transposition: the adjoint of a forward prefix sum is a reverse
/// prefix sum of the output cotangent and vice versa, matching JAX's `_cumsum_transpose_rule`. The scanned
/// dimension must be static and unsharded, as documented on [`cumulative_abstract`]. The element data type must be
/// real or complex numeric.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct CumulativeSumOperation {
    /// Scanned axis, in the operand's own coordinate system.
    axis: usize,

    /// Whether the scan accumulates from the end of the scanned axis toward its start.
    reverse: bool,
}

impl CumulativeSumOperation {
    /// Creates a new forward [`CumulativeSumOperation`] scanning along `axis`. The scanned extent is not part of the
    /// operation payload: it is recoverable from the staged input type wherever a rule needs it.
    #[inline]
    pub fn new(axis: usize) -> Self {
        Self { axis, reverse: false }
    }

    /// Returns this operation with its scan direction set to `reverse`, accumulating from the end of the scanned
    /// axis toward its start.
    #[inline]
    pub fn with_reverse(mut self, reverse: bool) -> Self {
        self.reverse = reverse;
        self
    }

    /// Returns the scanned axis.
    #[inline]
    pub fn axis(&self) -> usize {
        self.axis
    }

    /// Returns whether the scan accumulates from the end of the scanned axis toward its start.
    #[inline]
    pub fn reverse(&self) -> bool {
        self.reverse
    }
}

impl Display for CumulativeSumOperation {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.render(formatter, 0)
    }
}

impl Operation for CumulativeSumOperation {
    type Type = ArrayType;

    #[inline]
    fn name(&self) -> &'static str {
        CUMULATIVE_SUM_OPERATION_NAME
    }

    fn infer_output_types(
        &self,
        input_types: &[ArrayType],
        _region_interfaces: &[RegionInterface<ArrayType>],
    ) -> Result<Vec<ArrayType>, TypeError> {
        check_count!("input", input_types, 1, TypeError);
        Ok(vec![cumulative_sum_abstract(&input_types[0], self.axis)?])
    }

    fn render(&self, formatter: &mut std::fmt::Formatter<'_>, indentation: usize) -> std::fmt::Result {
        OperationFormatter::new(formatter, indentation, self.name())?.bracketed(|operation| {
            operation.field("axis", self.axis)?;
            if self.reverse {
                operation.field("reverse", self.reverse)?;
            }
            Ok(())
        })
    }
}

/// Returns the output [`ArrayType`] of a cumulative sum of `input` along `axis`, layering the summation element
/// data-type domain (real or complex numeric, plus the payload-free structural zero) onto the geometry validated by
/// [`cumulative_abstract`]. The eager kernel and the operation's type inference share this rule, so a directly
/// invoked [`CumulativeSum`] capability rejects exactly what a staged program rejects.
pub(crate) fn cumulative_sum_abstract(input: &ArrayType, axis: usize) -> Result<ArrayType, TypeError> {
    let data_type = input.data_type();
    if !data_type.is_numeric() && data_type != DataType::Zero {
        return Err(TypeError::invalid(format!(
            "`{CUMULATIVE_SUM_OPERATION_NAME}` requires numeric inputs but got {data_type}"
        )));
    }
    cumulative_abstract(input, axis, CUMULATIVE_SUM_OPERATION_NAME)
}

impl<C: Domain<Type = ArrayType, Value: CumulativeSum>> InterpretableOperation<C> for CumulativeSumOperation {
    fn interpret<D: InterpretationDriver<C>>(
        &self,
        _context: &C,
        _driver: &D,
        inputs: &[C::Value],
    ) -> Result<Vec<C::Value>, ProgramError> {
        check_count!("input", inputs, 1, ProgramError);
        Ok(vec![match self.reverse {
            true => inputs[0].reverse_cumulative_sum(self.axis)?,
            false => inputs[0].cumulative_sum(self.axis)?,
        }])
    }
}

// Partial evaluation defers to the default fold-or-residualize behavior of `Program::partially_evaluate`.
impl<C: Context<Type = ArrayType>> PartiallyEvaluatableOperation<C> for CumulativeSumOperation where
    C::Operation: From<CumulativeSumOperation>
{
}

// The scanned axis is expressed in the per-item coordinate system, so the rule lifts it past the inserted batch
// dimension with `lift_cumulative_axis` and re-interprets the lifted scan over the physical batched value. Padding
// along a *scanned* ragged axis is neutralized with the zero identity first, and the operand's ragged axes ride
// through onto the result because a scan consumes none of them.
impl<C: Context<Type = ArrayType>, P: RaggedArrayBatchingPolicy<C>> BatchableOperation<C, ArrayBatching<P>>
    for CumulativeSumOperation
where
    CumulativeSumOperation: InterpretableOperation<C>,
{
    fn batch<D: BatchingDriver<C, ArrayBatching<P>>>(
        &self,
        context: &BatchingContext<C, ArrayBatching<P>>,
        _driver: &D,
        inputs: &[ArrayBatch<C::Value>],
    ) -> Result<BatchedOutputs<C, ArrayBatching<P>>, BatchingError> {
        check_count!("input", inputs, 1, ProgramError);
        // A replicated operand carries no inserted batch dimension, so its scanned axis needs no shift. Ragged axes
        // are packed positions in both cases, and so the masking and rewrapping below use the lifted axis.
        let (lifted_axis, output_batch_axis) = match inputs[0].batch_axis_position() {
            Some(batch_axis) => {
                let (lifted_axis, output_axis) = lift_cumulative_axis(self.axis, batch_axis);
                (lifted_axis, BatchAxis::from_position(output_axis))
            }
            None => (self.axis, BatchAxis::replicated()),
        };
        let input = match inputs[0].ragged_axes().iter().any(|ragged_axis| ragged_axis.axis() == lifted_axis) {
            true => P::mask_identity_input(context, &inputs[0], &[lifted_axis], RaggedMaskIdentity::Zero)?,
            false => inputs[0].clone(),
        };
        let lifted = Self { axis: lifted_axis, reverse: self.reverse };
        let mut outputs = lifted.interpret_with_batch_axes(
            context,
            std::slice::from_ref(&input),
            std::slice::from_ref(&output_batch_axis),
        )?;
        check_count!("output", outputs, 1, ProgramError);
        // Interpretation carries values rather than batch metadata, so the operand's ragged axes are restored here.
        let output = ArrayBatch::new(outputs.remove(0).into_value(), output_batch_axis)?
            .with_ragged_axes(input.ragged_axes().to_vec())?;
        Ok(BatchedOutputs::new(vec![output], Vec::new()))
    }
}

// A prefix sum is linear in its operand, so the output tangent is the same prefix sum applied to the operand
// tangent. The composite array universe reaches this rule through the default projected fall-through of
// `MemberDifferentiableOperation`, because the operation is shape-preserving and its operand never needs the
// replication a broadcasting elementwise member does.
impl<C: Context<Type = ArrayType>> DifferentiableOperation<C> for CumulativeSumOperation
where
    C::Operation: From<CumulativeSumOperation>,
    C::Value: CumulativeSum,
{
    fn jvp<D: DifferentiationDriver<C>>(
        &self,
        _context: &C,
        _driver: &D,
        inputs: &[DifferentiationDual<C::Value>],
    ) -> Result<Vec<DifferentiationDual<C::Value>>, DifferentiationError> {
        check_count!("input", inputs, 1, ProgramError);
        let scan = |value: &C::Value| match self.reverse {
            true => value.reverse_cumulative_sum(self.axis),
            false => value.cumulative_sum(self.axis),
        };
        let primal = scan(inputs[0].primal())?;
        let tangent = match inputs[0].tangent() {
            MaybeZero::Zero(_) => MaybeZero::Zero(primal.r#type().tangent()?),
            MaybeZero::Value(tangent) => MaybeZero::Value(scan(tangent)?),
        };
        Ok(vec![DifferentiationDual::new(primal, tangent)?])
    }
}

// A forward prefix sum sends input element `i` into every output element `j >= i`, so the cotangent of input `i` is
// the sum of the output cotangents `j >= i` — a reverse prefix sum. The adjoint of a reverse prefix sum is
// symmetrically a forward one, which is why the operation is closed under transposition and needs no companion
// primitive.
impl<V: Value<Type = ArrayType>, O> TransposableOperation<V, O> for CumulativeSumOperation
where
    O: Operation<Type = ArrayType> + From<CumulativeSumOperation>,
{
    fn transpose<D: TranspositionDriver<V, O>>(
        &self,
        _context: &mut TracingContext<V, O>,
        _driver: &D,
        inputs: &[PartialValue<Tracer<TracingContext<V, O>>>],
        outputs: &[MaybeZero<Tracer<TracingContext<V, O>>>],
    ) -> Result<Vec<MaybeZero<Tracer<TracingContext<V, O>>>>, DifferentiationError> {
        check_count!("input", inputs, 1, ProgramError);
        check_count!("output", outputs, 1, ProgramError);
        match &outputs[0] {
            MaybeZero::Zero(_) => Ok(vec![MaybeZero::Zero(inputs[0].r#type().cotangent()?)]),
            MaybeZero::Value(cotangent) => Ok(vec![MaybeZero::Value(match self.reverse {
                true => cotangent.cumulative_sum(self.axis)?,
                false => cotangent.reverse_cumulative_sum(self.axis)?,
            })]),
        }
    }
}

/// Value-level cumulative summation capability.
///
/// [`CumulativeSum`] is the receiver-style entry point for staging or executing a [`CumulativeSumOperation`]: it
/// scans the receiver along `axis`, returning a value of the receiver's own type whose element `i` along that axis
/// holds the sum of the receiver's elements `0..=i` (or `i..` for the reverse direction).
pub trait CumulativeSum: Sized {
    /// Returns the inclusive prefix sum of `self` along `axis`.
    fn cumulative_sum(&self, axis: usize) -> Result<Self, ProgramError>;

    /// Returns the inclusive suffix sum of `self` along `axis` (i.e., the prefix sum accumulated from the end of the
    /// axis toward its start).
    fn reverse_cumulative_sum(&self, axis: usize) -> Result<Self, ProgramError>;
}

// Any context-carrying value scans by binding a `CumulativeSumOperation` through its own context. The
// `From<CumulativeSumOperation>` bound makes this disjoint from the eager value types (whose context operation is
// `ConstantOperation`), so it covers the transform tracers without conflicting with the concrete implementations.
impl<V: Value<Type = ArrayType>> CumulativeSum for V
where
    V::DispatchDomain: Context<Type = ArrayType>,
    <V::DispatchDomain as Domain>::Operation: From<CumulativeSumOperation>,
{
    #[inline]
    fn cumulative_sum(&self, axis: usize) -> Result<Self, ProgramError> {
        Ok(self
            .dispatch_domain()
            .bind(CumulativeSumOperation::new(axis), Vec::new(), &[self.clone()])?
            .remove(0))
    }

    #[inline]
    fn reverse_cumulative_sum(&self, axis: usize) -> Result<Self, ProgramError> {
        Ok(self
            .dispatch_domain()
            .bind(CumulativeSumOperation::new(axis).with_reverse(true), Vec::new(), &[self.clone()])?
            .remove(0))
    }
}

#[cfg(test)]
mod tests {
    use indoc::indoc;
    use num_complex::Complex as ComplexNumber;
    use pretty_assertions::assert_eq;

    use crate::arrays::batching::DynamicArrayBatchingPolicy;
    use crate::arrays::{
        Array, ArrayIrOperation, ArrayIrValue, DataType, Dimension, DimensionBounds, DimensionType, DimensionVariable,
        LogicalMesh, MeshAxis, MeshAxisType, RaggedAxis, Shape, Sharding, ShardingDimension,
    };
    use crate::contexts::{EagerContext, ProjectedContext, StagingContext};
    use crate::macros::{check_operation_batching, check_operation_differentiation, check_operation_transposition};
    use crate::parameters::Placeholder;
    use crate::programs::{EmptyRegionDriver, ValueProjection};

    use super::*;

    #[test]
    fn test_cumulative_sum_operation_type_inference() {
        // The output type follows the staged input type exactly, and complex payloads are accepted alongside the
        // real numeric ones.
        let operation = CumulativeSumOperation::new(1);
        let input = ArrayType::new_static(DataType::F64, [3, 2]);
        assert_eq!(operation.infer_output_types(std::slice::from_ref(&input), &[]), Ok(vec![input]));
        let complex = ArrayType::new_static(DataType::C64, [3, 2]);
        assert_eq!(operation.infer_output_types(std::slice::from_ref(&complex), &[]), Ok(vec![complex]));

        // Non-numeric payloads have no summation.
        assert_eq!(
            operation.infer_output_types(&[ArrayType::new_static(DataType::Boolean, [3, 2])], &[]),
            Err(TypeError::invalid("`cumulative_sum` requires numeric inputs but got bool".to_string())),
        );

        // The geometry rules of the family are enforced against the staged input type.
        assert_eq!(
            operation.infer_output_types(&[ArrayType::new_static(DataType::F64, [3])], &[]),
            Err(TypeError::invalid("`cumulative_sum` axis 1 is out of bounds for rank 1".to_string())),
        );
        let dynamic = ArrayType::new(
            DataType::F64,
            Shape::new(vec![
                Dimension::Static(3),
                Dimension::Dynamic(DimensionVariable::new("length", DimensionBounds::new(0, Some(4)).unwrap())),
            ]),
        );
        assert_eq!(
            operation.infer_output_types(std::slice::from_ref(&dynamic), &[]),
            Err(TypeError::invalid(format!(
                "`cumulative_sum` requires a static scanned dimension but axis 1 of {dynamic} is dynamic"
            ))),
        );
        let mesh = LogicalMesh::new(vec![MeshAxis::new("x", 2, MeshAxisType::Explicit).unwrap()]).unwrap();
        let sharded = ArrayType::new_static(DataType::F64, [3, 2])
            .with_sharding(
                Sharding::new(mesh, vec![ShardingDimension::replicated(), ShardingDimension::sharded(["x"])]).unwrap(),
            )
            .unwrap();
        assert_eq!(
            operation.infer_output_types(std::slice::from_ref(&sharded), &[]),
            Err(TypeError::invalid(format!(
                "`cumulative_sum` requires an unsharded scanned dimension but axis 1 of {sharded} is sharded"
            ))),
        );
    }

    #[test]
    fn test_cumulative_sum_operation_rendering() {
        // The scan direction renders only when it is set, keeping the common forward scan compact.
        assert_eq!(CumulativeSumOperation::new(1).to_string(), "cumulative_sum [axis=1]");
        assert_eq!(
            CumulativeSumOperation::new(0).with_reverse(true).to_string(),
            "cumulative_sum [axis=0, reverse=true]",
        );
        assert_eq!(CumulativeSumOperation::new(0).with_reverse(false), CumulativeSumOperation::new(0));
    }

    #[test]
    fn test_cumulative_sum_operation_interpretation() {
        let context = EagerContext::<Array>::new();
        let interpret = |operation: &CumulativeSumOperation, input: &Array| {
            operation.interpret(&context, &EmptyRegionDriver, std::slice::from_ref(input)).unwrap().remove(0)
        };

        // Forward scans accumulate prefixes and reverse scans accumulate suffixes, along the selected axis only.
        let input = Array::matrix(2, 3, vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0]);
        assert_eq!(
            interpret(&CumulativeSumOperation::new(1), &input),
            Array::matrix(2, 3, vec![1.0, 3.0, 6.0, 4.0, 9.0, 15.0]),
        );
        assert_eq!(
            interpret(&CumulativeSumOperation::new(1).with_reverse(true), &input),
            Array::matrix(2, 3, vec![6.0, 5.0, 3.0, 15.0, 11.0, 6.0]),
        );
        assert_eq!(
            interpret(&CumulativeSumOperation::new(0), &input),
            Array::matrix(2, 3, vec![1.0, 2.0, 3.0, 5.0, 7.0, 9.0]),
        );

        // A zero-length scanned axis has nothing to accumulate and keeps the operand's exact type.
        let empty = Array::new(ArrayType::new_static(DataType::F32, [0, 2]), Vec::new()).unwrap();
        assert_eq!(interpret(&CumulativeSumOperation::new(0), &empty), empty);

        // Low-precision payloads accumulate in their own encoding, so each partial sum is rounded to it: `f8e4m3fn`
        // cannot represent 7 and rounds the third prefix to the nearest representable value.
        let low_precision = Array::from_f64s(ArrayType::new_static(DataType::F8E4M3FN, [4]), vec![1.0, 2.0, 4.0, 8.0]);
        assert_eq!(
            interpret(&CumulativeSumOperation::new(0), &low_precision),
            Array::from_f64s(ArrayType::new_static(DataType::F8E4M3FN, [4]), vec![1.0, 3.0, 7.0, 15.0]),
        );

        // Complex payloads accumulate both components.
        let complex = Array::vector(vec![
            ComplexNumber::new(1.0_f64, 1.0),
            ComplexNumber::new(2.0, -1.0),
            ComplexNumber::new(3.0, 5.0),
        ]);
        assert_eq!(
            interpret(&CumulativeSumOperation::new(0), &complex),
            Array::vector(vec![
                ComplexNumber::new(1.0_f64, 1.0),
                ComplexNumber::new(3.0, 0.0),
                ComplexNumber::new(6.0, 5.0),
            ]),
        );
    }

    #[test]
    fn test_cumulative_sum_capability_over_eager_arrays() {
        // The capability is the receiver-style entry point of the same kernel, in both scan directions, and it
        // reports the operation's own validation errors instead of panicking.
        let input = Array::vector(vec![1.0, 2.0, 3.0]);
        assert_eq!(input.cumulative_sum(0), Ok(Array::vector(vec![1.0, 3.0, 6.0])));
        assert_eq!(input.reverse_cumulative_sum(0), Ok(Array::vector(vec![6.0, 5.0, 3.0])));
        assert_eq!(
            input.cumulative_sum(1),
            Err(ProgramError::Type(TypeError::invalid(
                "`cumulative_sum` axis 1 is out of bounds for rank 1".to_string(),
            ))),
        );
    }

    #[test]
    fn test_cumulative_sum_operation_batches_replicated_input_as_pass_through() {
        check_operation_batching!(
            @exact,
            operation = CumulativeSumOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@replicated, Array::vector(vec![1.0, 2.0, 3.0]))],
                outputs = [(@replicated, Array::vector(vec![1.0, 3.0, 6.0]))],
            }],
        );
    }

    #[test]
    fn test_cumulative_sum_operation_batches_along_the_shifted_axis() {
        // Physical input is [2 batch items, 3 columns] mapped at axis 0, so the per-item axis 0 scans physical axis
        // 1 and each batch item accumulates independently.
        check_operation_batching!(
            @exact,
            operation = CumulativeSumOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@mapped(axis = 0), Array::matrix(2, 3, vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0]))],
                outputs = [(@mapped(axis = 0), Array::matrix(2, 3, vec![1.0, 3.0, 6.0, 4.0, 9.0, 15.0]))],
            }],
        );

        // With the batch dimension inserted after the scanned axis, the scanned axis keeps its position.
        check_operation_batching!(
            @exact,
            operation = CumulativeSumOperation::new(0),
            axis_size = 3,
            cases = [{
                inputs = [(@mapped(axis = 1), Array::matrix(2, 3, vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0]))],
                outputs = [(@mapped(axis = 1), Array::matrix(2, 3, vec![1.0, 2.0, 3.0, 5.0, 7.0, 9.0]))],
            }],
        );
    }

    #[test]
    fn test_cumulative_sum_operation_passes_ragged_axes_through_unmasked() {
        // Per item, a ragged `[length]` row is scanned along its dense trailing axis, so the ragged axis is not the
        // scanned one: nothing needs masking, the axis rides through onto the result unchanged, and — because the
        // scan consumes no axis — the rule claims no consumption evidence.
        let variable = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let extents = Array::vector(vec![1_i32, 3]);
        let input = ArrayBatch::new(
            Array::from_f64s(ArrayType::new_static(DataType::F32, [2, 3, 2]), (1..=12).map(f64::from).collect()),
            BatchAxis::new(0),
        )
        .unwrap()
        .with_ragged_axes(vec![RaggedAxis::new(1, extents.clone(), variable.clone(), vec![0])])
        .unwrap();
        let (outputs, evidence) = CumulativeSumOperation::new(1)
            .batch(&BatchingContext::new(EagerContext::<Array>::new(), 2), &EmptyRegionDriver, &[input])
            .unwrap()
            .into_parts();

        assert_eq!(outputs.len(), 1);
        assert_eq!(outputs[0].batch_axis(), BatchAxis::new(0));
        assert_eq!(outputs[0].ragged_axes(), &[RaggedAxis::new(1, extents, variable, vec![0])]);
        let expected = vec![1.0, 3.0, 3.0, 7.0, 5.0, 11.0, 7.0, 15.0, 9.0, 19.0, 11.0, 23.0];
        assert_eq!(outputs[0].value().to_f64s(), expected);
        assert!(evidence.is_empty());
    }

    #[test]
    fn test_cumulative_sum_operation_masks_ragged_padding_on_the_scanned_axis() {
        // Scanning a ragged axis would accumulate its padding into every later live prefix, so the rule asks the
        // policy to neutralize that padding first. Static array batching cannot, and says so rather than silently
        // scanning padding.
        let variable = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let input = ArrayBatch::new(Array::matrix(2, 3, vec![1.0_f32; 6]), BatchAxis::new(0))
            .unwrap()
            .with_ragged_axes(vec![RaggedAxis::new(1, Array::vector(vec![1_i32, 3]), variable, vec![0])])
            .unwrap();
        assert_eq!(
            CumulativeSumOperation::new(0).batch(
                &BatchingContext::new(EagerContext::<Array>::new(), 2),
                &EmptyRegionDriver,
                &[input],
            ),
            Err(BatchingError::UnsupportedOperation {
                message: "static array batching cannot identity-mask bounded ragged dimension `length` on axis 1 \
                          with `Zero`"
                    .to_string(),
            }),
        );

        // The composite dynamic policy can, and stages the mask ahead of the scan: the padded positions of the
        // scanned axis are selected away in favor of the operation's zero identity, and the ragged axis survives on
        // the result because a scan consumes no axis.
        type TraceContext = TracingContext<ArrayIrValue<Array>, ArrayIrOperation<Array>>;
        let trace = TraceContext::new();
        let items = DimensionVariable::new("items", DimensionBounds::new(1, Some(9)).unwrap());
        let length = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let batch_extent = trace.input(DimensionType::new(items.clone()).into());
        let packed = trace.input(
            ArrayType::new(DataType::F32, Shape::new(vec![Dimension::Dynamic(items.clone()), Dimension::Static(3)]))
                .into(),
        );
        let extents = trace.input(ArrayType::new(DataType::I32, Shape::new(vec![Dimension::Dynamic(items)])).into());
        let context = BatchingContext::<_, ArrayBatching<DynamicArrayBatchingPolicy>>::with_policy(
            ProjectedContext::new(trace.clone()),
            batch_extent,
        );
        let input = ArrayBatch::new(packed.into_projected().unwrap(), BatchAxis::new(0))
            .unwrap()
            .with_ragged_axes(vec![RaggedAxis::new(1, extents.into_projected().unwrap(), length.clone(), vec![0])])
            .unwrap();
        // The per-item scan of axis 0 is the packed axis 1 that carries the ragged extents.
        let (outputs, evidence) =
            CumulativeSumOperation::new(0).batch(&context, &EmptyRegionDriver, &[input]).unwrap().into_parts();
        assert_eq!(outputs.len(), 1);
        assert_eq!(outputs[0].batch_axis(), BatchAxis::new(0));
        assert_eq!(outputs[0].ragged_axes().len(), 1);
        assert_eq!(outputs[0].ragged_axes()[0].axis(), 1);
        assert_eq!(outputs[0].ragged_axes()[0].dimension(), &length);
        assert!(evidence.is_empty());

        let output_id = outputs.into_iter().next().unwrap().into_value().into_value().atom_id().unwrap();
        drop(context);
        let program = trace
            .builder()
            .borrow()
            .clone()
            .build::<Vec<ArrayIrValue<Array>>, Vec<ArrayIrValue<Array>>>(
                vec![output_id],
                vec![Placeholder, Placeholder, Placeholder],
                vec![Placeholder],
            )
            .unwrap();
        assert_eq!(
            program.to_string(),
            indoc! {"
                lambda %0:dimension<items ∈ [1, 9)>, %1:f32[items, 3], %2:i32[items] .
                let %3:dimension<items ∈ [1, 9)> = dimension_size [axis=0] %1
                    %4:dimension<3> = constant [value=3]
                    %5:i32[3] = iota [type=i32[3], dimension=0]
                    %6:i32[items, 3] = broadcast [output_axes=[1]] %5 %3 %4
                    %7:i32[items, 3] = broadcast [output_axes=[0]] %2 %3 %4
                    %8:bool[items, 3] = compare [direction=LessThan] %6 %7
                    %9:f32[items, 3] = zero_like %1
                    %10:f32[items, 3] = select %8 %1 %9
                    %11:f32[items, 3] = cumulative_sum [axis=1] %10
                in (%11)
            "}
            .trim_end(),
        );
    }

    #[test]
    fn test_cumulative_sum_operation_differentiation() {
        // The primitive is linear, so the tangent is the same scan of the operand tangent in both directions.
        check_operation_differentiation!(
            @approx(step = 0.125, epsilon = 1e-6),
            operation = CumulativeSumOperation::new(0),
            cases = [{
                primals = [Array::vector(vec![1.0, 2.0, 3.0])],
                tangents = [Array::vector(vec![1.0, 1.0, 1.0])],
                primal_outputs = [Array::vector(vec![1.0, 3.0, 6.0])],
                tangent_outputs = [Array::vector(vec![1.0, 2.0, 3.0])],
            }],
        );
        check_operation_differentiation!(
            @approx(step = 0.125, epsilon = 1e-6),
            operation = CumulativeSumOperation::new(0).with_reverse(true),
            cases = [{
                primals = [Array::vector(vec![1.0, 2.0, 3.0])],
                tangents = [Array::vector(vec![1.0, 1.0, 1.0])],
                primal_outputs = [Array::vector(vec![6.0, 5.0, 3.0])],
                tangent_outputs = [Array::vector(vec![3.0, 2.0, 1.0])],
            }],
        );
    }

    #[test]
    fn test_cumulative_sum_operation_transposition_flips_the_scan_direction() {
        // The adjoint of a forward prefix sum is a reverse prefix sum of the output cotangent, staged as the same
        // primitive with its `reverse` flag flipped, and vice versa.
        check_operation_transposition!(
            @exact,
            operation = CumulativeSumOperation::new(0),
            cases = [{
                inputs = [(@linear(type = ArrayType::new_static(DataType::F64, [3])))],
                output_cotangents = [Array::vector(vec![1.0, 1.0, 1.0])],
                input_cotangents = [Array::vector(vec![3.0, 2.0, 1.0])],
                pullback = indoc! {"
                    lambda %0:f64[3] .
                    let %1:f64[3] = cumulative_sum [axis=0, reverse=true] %0
                    in (%1)
                "},
            }],
        );
        check_operation_transposition!(
            @exact,
            operation = CumulativeSumOperation::new(0).with_reverse(true),
            cases = [{
                inputs = [(@linear(type = ArrayType::new_static(DataType::F64, [3])))],
                output_cotangents = [Array::vector(vec![1.0, 1.0, 1.0])],
                input_cotangents = [Array::vector(vec![1.0, 2.0, 3.0])],
                pullback = indoc! {"
                    lambda %0:f64[3] .
                    let %1:f64[3] = cumulative_sum [axis=0] %0
                    in (%1)
                "},
            }],
        );
    }
}
