//! Contains the [`CumulativeLogSumExpOperation`], the running stable `log(sum(exp(x)))` member of the cumulative
//! family, together with the [`CumulativeLogSumExp`] staging capability and every rule the member does not choose
//! for itself, all generated by `define_cumulative_operation!`.

// TODO(eaplatanios): Review this module.

use std::fmt::Display;

use crate::arrays::{ArrayBatch, ArrayBatchingPolicy, ArrayType, RaggedArrayExtentBatchingPolicy, RaggedMaskIdentity};
use crate::batching::{
    BatchAxis, BatchableOperation, BatchedOutputs, BatchingContext, BatchingDriver, BatchingError,
    InterpretableBatchableOperation,
};
use crate::contexts::{Context, Domain};
use crate::differentiation::{
    DifferentiableOperation, DifferentiableType, DifferentiationDriver, DifferentiationDual, DifferentiationError,
};
use crate::interpretation::{InterpretableOperation, InterpretationDriver};
use crate::macros::{check_count, impl_non_transposable_operation};
use crate::operations::arithmetic::AddOperation;
use crate::operations::constants::zero::ZeroOperation;
use crate::operations::cumulative::{
    cumulative_abstract, define_cumulative_operation, jvp_through_associative_scan, lift_cumulative_axis,
};
use crate::operations::exponential::{
    LogAddExp, LogAddExpOperation, is_log_add_exp_identity_data_type, log_add_exp_identity_data_type_error,
};
use crate::operations::manipulation::concatenation::ConcatenateOperation;
use crate::operations::manipulation::padding::PadOperation;
use crate::operations::manipulation::slicing::SliceOperation;
use crate::partial::PartiallyEvaluatableOperation;
use crate::programs::{
    MaybeZero, Operation, OperationFormatter, OperationProvider, ProgramError, RegionInterface, TypeError, Typed, Value,
};

define_cumulative_operation! {
    /// Primitive representing one inclusive running `log(sum(exp(x)))` along a single array axis.
    ///
    /// Output element `i` along [`axis`](Self::axis) holds the stable `log(sum(exp(x)))` of input elements `0..=i`,
    /// or the stable `log(sum(exp(x)))` of elements `i..` when [`reverse`](Self::reverse) is set. The output type is
    /// the input type, so a `cumulative_log_sum_exp` is a shape-preserving unary primitive.
    ///
    /// Padding is filled with the element type's lowest value, which must be an identity of the rounded pairwise
    /// [`LogAddExp`] operation. True negative infinity satisfies this contract, as do finite sentinels that round
    /// back to the other input after each pairwise combination. Such sentinels remain neutral for any prefix length.
    /// [`DataType::F8E8M0FNU`](crate::arrays::DataType::F8E8M0FNU) and
    /// [`DataType::F6E2M3FN`](crate::arrays::DataType::F6E2M3FN) have no suitable identity and are rejected.
    /// The scanned dimension must be static and unsharded, as documented on [`cumulative_abstract`].
    ///
    /// Each prefix is accumulated by folding the pairwise [`LogAddExp`] primitive, which is stable over the whole
    /// real range but is a different expression from the max-shifted reduction that
    /// [`ReductionKind::LogSumExp`](crate::operations::reductions::ReductionKind::LogSumExp) evaluates, so the two can
    /// round differently in their last bits.
    operation = CumulativeLogSumExpOperation,
    name = CUMULATIVE_LOG_SUM_EXP_OPERATION_NAME = "cumulative_log_sum_exp",
    abstract_rule = cumulative_log_sum_exp_abstract,
    element_domain = |data_type| is_log_add_exp_identity_data_type(data_type),
    element_domain_error = log_add_exp_identity_data_type_error(CUMULATIVE_LOG_SUM_EXP_OPERATION_NAME, data_type),
    ragged_identity = RaggedMaskIdentity::Lowest,
    combine_operation = LogAddExpOperation<ArrayType>,
    combine = |left, right| left.log_add_exp(right),
    /// Value-level cumulative `log(sum(exp(x)))` capability.
    ///
    /// [`CumulativeLogSumExp`] is the receiver-style entry point for staging or executing a
    /// [`CumulativeLogSumExpOperation`]: it scans the receiver along `axis`, returning a value of the receiver's own
    /// type whose element `i` along that axis holds the stable `log(sum(exp(x)))` of the receiver's elements `0..=i`
    /// (or `i..` for the reverse direction).
    capability = CumulativeLogSumExp::{cumulative_log_sum_exp, reverse_cumulative_log_sum_exp},
}

#[cfg(test)]
mod tests {
    use indoc::indoc;
    use pretty_assertions::assert_eq;

    use crate::arrays::batching::DynamicArrayExtentBatchingPolicy;
    use crate::arrays::{
        Array, ArrayIrOperation, ArrayIrValue, DataType, Dimension, DimensionBounds, DimensionType, DimensionVariable,
        LogicalMesh, MeshAxis, MeshAxisType, RaggedAxis, Shape, Sharding, ShardingDimension, f4e2m1fn, f8e4m3fnuz,
    };
    use crate::contexts::{EagerContext, ProjectedContext, StagingContext};
    use crate::macros::{check_operation_batching, check_operation_differentiation};
    use crate::parameters::Placeholder;
    use crate::programs::{EmptyRegionDriver, ValueProjection};
    use crate::tracing::TracingContext;

    use super::*;

    // Pairwise stable `log(exp(a) + exp(b))`, spelled out so that the expected values below pin the construction
    // the scan folds rather than an equivalent-in-exact-arithmetic alternative.
    fn log_add_exp(left: f64, right: f64) -> f64 {
        let delta = left - right;
        match delta.is_nan() {
            true => left + right,
            false => left.max(right) + (-delta.abs()).exp().ln_1p(),
        }
    }

    #[test]
    fn test_cumulative_log_sum_exp() {
        // The scan direction renders only when it is set, keeping the common forward scan compact.
        assert_eq!(CumulativeLogSumExpOperation::new(1).to_string(), "cumulative_log_sum_exp [axis=1]");
        assert_eq!(
            CumulativeLogSumExpOperation::new(0).with_reverse(true).to_string(),
            "cumulative_log_sum_exp [axis=0, reverse=true]",
        );
        assert_eq!(CumulativeLogSumExpOperation::new(0).with_reverse(false), CumulativeLogSumExpOperation::new(0),);
    }

    #[test]
    fn test_cumulative_log_sum_exp_type_inference() {
        // The output type follows the staged input type exactly.
        let operation = CumulativeLogSumExpOperation::new(1);
        let input = ArrayType::new_static(DataType::F64, [3, 2]);
        assert_eq!(operation.infer_output_types(std::slice::from_ref(&input), &[]), Ok(vec![input]));

        // The exponential and the logarithm have no meaning for the integer, Boolean, token, structural-zero, or
        // complex element types.
        for data_type in [DataType::I32, DataType::Boolean, DataType::C64, DataType::Token, DataType::Zero] {
            assert_eq!(
                operation.infer_output_types(&[ArrayType::new_static(data_type, [3, 2])], &[]),
                Err(TypeError::invalid(format!(
                    "`cumulative_log_sum_exp` requires real floating-point inputs but got `{data_type}`"
                ))),
            );
        }

        // `f8e8m0fnu` is floating-point but encodes bare positive exponents, so it has neither a zero nor a sign, and
        // its smallest element exponentiates to one instead of acting as the combining operator's identity. Padded
        // and empty prefixes would climb rather than stay neutral, so the format is rejected outright.
        assert_eq!(
            operation.infer_output_types(&[ArrayType::new_static(DataType::F8E8M0FNU, [3, 2])], &[]),
            Err(TypeError::invalid(
                "`cumulative_log_sum_exp` requires a floating-point format whose lowest value is a `log_add_exp` \
                 identity but got `f8e8m0fnu`"
                    .to_string(),
            )),
        );

        // The lowest `f6e2m3fn` value already changes when combined with one more copy of itself.
        assert_eq!(
            operation.infer_output_types(&[ArrayType::new_static(DataType::F6E2M3FN, [3, 2])], &[]),
            Err(TypeError::invalid(
                "`cumulative_log_sum_exp` requires a floating-point format whose lowest value is a \
                 `log_add_exp` identity but got `f6e2m3fn`"
                    .to_string(),
            )),
        );
        // These finite sentinels are identities after every rounded pairwise combination.
        for data_type in [DataType::F4E2M1FN, DataType::F8E4M3B11FNUZ, DataType::F6E3M2FN] {
            let input_type = ArrayType::new_static(data_type, [3, 2]);
            assert_eq!(operation.infer_output_types(&[input_type.clone()], &[]), Ok(vec![input_type]));
        }

        // The geometry rules of the family are enforced against the staged input type.
        assert_eq!(
            operation.infer_output_types(&[ArrayType::new_static(DataType::F64, [3])], &[]),
            Err(TypeError::invalid("`cumulative_log_sum_exp` axis 1 is out of bounds for rank 1".to_string())),
        );
        let dynamic = ArrayType::new(
            DataType::F64,
            Shape::new(vec![
                Dimension::Static(3),
                Dimension::Dynamic(DimensionVariable::new("length", DimensionBounds::new(0, Some(4)).unwrap())),
            ]),
        );
        assert_eq!(
            operation.infer_output_types(std::slice::from_ref(&dynamic), &[]),
            Err(TypeError::invalid(format!(
                "`cumulative_log_sum_exp` requires a static scanned dimension but axis 1 of {dynamic} is dynamic"
            ))),
        );
        let mesh = LogicalMesh::new(vec![MeshAxis::new("x", 2, MeshAxisType::Explicit).unwrap()]).unwrap();
        let sharded = ArrayType::new_static(DataType::F64, [3, 2])
            .with_sharding(
                Sharding::new(mesh, vec![ShardingDimension::replicated(), ShardingDimension::sharded(["x"])]).unwrap(),
            )
            .unwrap();
        assert_eq!(
            operation.infer_output_types(std::slice::from_ref(&sharded), &[]),
            Err(TypeError::invalid(format!(
                "`cumulative_log_sum_exp` requires an unsharded scanned dimension but axis 1 of {sharded} is sharded"
            ))),
        );
    }

    #[test]
    fn test_cumulative_log_sum_exp_interpretation() {
        let context = EagerContext::<Array>::new();
        let interpret = |operation: &CumulativeLogSumExpOperation, input: &Array| {
            operation.interpret(&context, &EmptyRegionDriver, std::slice::from_ref(input)).unwrap().remove(0)
        };

        // Forward scans accumulate prefixes and reverse scans accumulate suffixes, along the selected axis only.
        let input = Array::vector(vec![1.0, 2.0, 3.0]).unwrap();
        let forward_second = log_add_exp(1.0, 2.0);
        let reverse_second = log_add_exp(3.0, 2.0);
        assert_eq!(
            interpret(&CumulativeLogSumExpOperation::new(0), &input),
            Array::vector(vec![1.0, forward_second, log_add_exp(forward_second, 3.0)]).unwrap(),
        );
        assert_eq!(
            interpret(&CumulativeLogSumExpOperation::new(0).with_reverse(true), &input),
            Array::vector(vec![log_add_exp(reverse_second, 1.0), reverse_second, 3.0]).unwrap(),
        );
        assert_eq!(
            interpret(
                &CumulativeLogSumExpOperation::new(0),
                &Array::matrix(2, 3, vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0]).unwrap()
            ),
            Array::matrix(
                2,
                3,
                vec![1.0, 2.0, 3.0, log_add_exp(1.0, 4.0), log_add_exp(2.0, 5.0), log_add_exp(3.0, 6.0)],
            )
            .unwrap(),
        );

        // The point of folding the guarded pairwise primitive: two equal operands add exactly `log(2)` at any
        // magnitude, where exponentiating directly would already have overflowed.
        assert_eq!(
            interpret(&CumulativeLogSumExpOperation::new(0), &Array::vector(vec![1000.0, 1000.0]).unwrap()),
            Array::vector(vec![1000.0, 1000.0 + std::f64::consts::LN_2]).unwrap(),
        );
        assert!((1000.0f64.exp() + 1000.0f64.exp()).ln().is_infinite());

        // Negative infinity is the combining operator's identity, so a prefix of `-inf` elements stays `-inf` and a
        // later finite element takes over exactly.
        assert_eq!(
            interpret(
                &CumulativeLogSumExpOperation::new(0),
                &Array::vector(vec![f64::NEG_INFINITY, f64::NEG_INFINITY, 2.0]).unwrap(),
            ),
            Array::vector(vec![f64::NEG_INFINITY, f64::NEG_INFINITY, 2.0]).unwrap(),
        );

        // Repeated rounded pairwise identities remain unchanged beyond the former fold-count limits.
        let input = Array::vector(vec![f4e2m1fn::MIN; 16]).unwrap();
        assert_eq!(interpret(&CumulativeLogSumExpOperation::new(0), &input), input);
        let input = Array::vector(vec![f8e4m3fnuz::MIN; 3000]).unwrap();
        assert_eq!(interpret(&CumulativeLogSumExpOperation::new(0), &input), input);

        // A zero-length scanned axis has nothing to accumulate and keeps the operand's exact type.
        let empty = Array::new(ArrayType::new_static(DataType::F32, [0, 2]), Vec::new()).unwrap();
        assert_eq!(interpret(&CumulativeLogSumExpOperation::new(0), &empty), empty);
    }

    #[test]
    fn test_cumulative_log_sum_exp_batching() {
        // A replicated operand carries no inserted batch dimension, so the scanned axis needs no shift.
        check_operation_batching!(
            @approx(epsilon = 1e-12),
            operation = CumulativeLogSumExpOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@replicated, Array::vector(vec![0.0, 0.0]).unwrap())],
                outputs = [(@replicated, Array::vector(vec![0.0, std::f64::consts::LN_2]).unwrap())],
            }],
        );

        // Physical input is [2 batch items, 2 columns] mapped at axis 0, so the per-item axis 0 scans physical axis
        // 1 and each batch item accumulates independently.
        check_operation_batching!(
            @approx(epsilon = 1e-12),
            operation = CumulativeLogSumExpOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@mapped(axis = 0), Array::matrix(2, 2, vec![0.0, 0.0, 1000.0, 1000.0]).unwrap())],
                outputs = [(@mapped(axis = 0), Array::matrix(
                    2,
                    2,
                    vec![0.0, std::f64::consts::LN_2, 1000.0, 1000.0 + std::f64::consts::LN_2],
                ).unwrap())],
            }],
        );

        // With the batch dimension inserted after the scanned axis, the scanned axis keeps its position.
        check_operation_batching!(
            @approx(epsilon = 1e-12),
            operation = CumulativeLogSumExpOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@mapped(axis = 1), Array::matrix(2, 2, vec![0.0, 1000.0, 0.0, 1000.0]).unwrap())],
                outputs = [(@mapped(axis = 1), Array::matrix(
                    2,
                    2,
                    vec![0.0, 1000.0, std::f64::consts::LN_2, 1000.0 + std::f64::consts::LN_2],
                ).unwrap())],
            }],
        );
    }

    #[test]
    fn test_cumulative_log_sum_exp_masks_ragged_padding_with_negative_infinity() {
        // Scanning a ragged axis would fold its padding into every later live prefix, so the rule asks the policy to
        // neutralize that padding with the combining operator's identity first. Static array batching cannot, and
        // says so rather than silently scanning padding.
        let variable = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let input = ArrayBatch::new(Array::matrix(2, 3, vec![1.0_f32; 6]).unwrap(), BatchAxis::new(0))
            .unwrap()
            .with_ragged_axes(vec![RaggedAxis::new(1, Array::vector(vec![1_i32, 3]).unwrap(), variable, vec![0])])
            .unwrap();
        assert_eq!(
            CumulativeLogSumExpOperation::new(0).batch(
                &BatchingContext::new(EagerContext::<Array>::new(), 2),
                &EmptyRegionDriver,
                &[input],
            ),
            Err(BatchingError::UnsupportedOperation {
                message: "static array batching cannot identity-mask bounded ragged dimension `length` on axis 1 \
                          with `Lowest`"
                    .to_string(),
            }),
        );

        // The composite dynamic policy can, and stages the mask ahead of the scan: the padded positions of the
        // scanned axis are selected away in favor of negative infinity, whose exponential is the inner sum's zero
        // identity, and the ragged axis survives on the result because a scan consumes no axis.
        type TraceContext = TracingContext<ArrayIrValue<Array>, ArrayIrOperation<Array>>;
        let trace = TraceContext::new();
        let items = DimensionVariable::new("items", DimensionBounds::new(1, Some(9)).unwrap());
        let length = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let batch_extent = trace.input(DimensionType::from(items.clone()).into());
        let packed = trace.input(
            ArrayType::new(DataType::F32, Shape::new(vec![Dimension::Dynamic(items.clone()), Dimension::Static(3)]))
                .into(),
        );
        let extents = trace.input(ArrayType::new(DataType::I32, Shape::new(vec![Dimension::Dynamic(items)])).into());
        let context = BatchingContext::<_, ArrayBatchingPolicy<DynamicArrayExtentBatchingPolicy>>::with_policy(
            ProjectedContext::new(trace.clone()),
            batch_extent,
        );
        let input = ArrayBatch::new(packed.into_projected().unwrap(), BatchAxis::new(0))
            .unwrap()
            .with_ragged_axes(vec![RaggedAxis::new(1, extents.into_projected().unwrap(), length.clone(), vec![0])])
            .unwrap();
        // The per-item scan of axis 0 is the packed axis 1 that carries the ragged extents.
        let (outputs, evidence) = CumulativeLogSumExpOperation::new(0)
            .batch(&context, &EmptyRegionDriver, &[input])
            .unwrap()
            .into_parts();
        assert_eq!(outputs.len(), 1);
        assert_eq!(outputs[0].batch_axis(), BatchAxis::new(0));
        assert_eq!(outputs[0].ragged_axes().len(), 1);
        assert_eq!(outputs[0].ragged_axes()[0].axis(), 1);
        assert_eq!(outputs[0].ragged_axes()[0].dimension(), &length);
        assert!(evidence.is_empty());

        let output_id = outputs.into_iter().next().unwrap().into_value().into_value().atom_id().unwrap();
        drop(context);
        let program = trace
            .builder()
            .borrow()
            .clone()
            .build::<Vec<ArrayIrValue<Array>>, Vec<ArrayIrValue<Array>>>(
                vec![output_id],
                vec![Placeholder, Placeholder, Placeholder],
                vec![Placeholder],
            )
            .unwrap();
        assert_eq!(
            program.to_string(),
            indoc! {"
                lambda %0:dimension<items ∈ [1, 9)>, %1:f32[items, 3], %2:i32[items] .
                let %3:dimension<items ∈ [1, 9)> = dimension_size [axis=0] %1
                    %4:dimension<3> = constant [value=3]
                    %5:i32[3] = iota [type=i32[3], dimension=0]
                    %6:i32[items, 3] = broadcast [output_axes=[1]] %5 %3 %4
                    %7:i32[items, 3] = broadcast [output_axes=[0]] %2 %3 %4
                    %8:bool[items, 3] = compare [direction=LessThan] %6 %7
                    %9:f32[] = constant [value=-inf]
                    %10:f32[items, 3] = broadcast [output_axes=[]] %9 %3 %4
                    %11:f32[items, 3] = select %8 %1 %10
                    %12:f32[items, 3] = cumulative_log_sum_exp [axis=1] %11
                in (%12)
            "}
            .trim_end(),
        );
    }

    #[test]
    fn test_cumulative_log_sum_exp_differentiation() {
        // The partial derivative with respect to each accumulated element is that element's softmax weight within
        // the prefix, so each output tangent is the softmax-weighted average of the operand tangents over it.
        let e = std::f64::consts::E;
        check_operation_differentiation!(
            @approx(step = 1e-4, epsilon = 1e-6),
            operation = CumulativeLogSumExpOperation::new(0),
            cases = [{
                primals = [Array::vector(vec![0.0, 1.0, 2.0]).unwrap()],
                tangents = [Array::vector(vec![1.0, 2.0, 3.0]).unwrap()],
                primal_outputs = [Array::vector(vec![0.0, (1.0 + e).ln(), (1.0 + e + e * e).ln()]).unwrap()],
                tangent_outputs = [Array::vector(vec![
                    1.0,
                    (1.0 + 2.0 * e) / (1.0 + e),
                    (1.0 + 2.0 * e + 3.0 * e * e) / (1.0 + e + e * e),
                ]).unwrap()],
            }],
        );
        check_operation_differentiation!(
            @approx(step = 1e-4, epsilon = 1e-6),
            operation = CumulativeLogSumExpOperation::new(0).with_reverse(true),
            cases = [{
                primals = [Array::vector(vec![0.0, 1.0, 2.0]).unwrap()],
                tangents = [Array::vector(vec![1.0, 2.0, 3.0]).unwrap()],
                primal_outputs = [Array::vector(vec![(1.0 + e + e * e).ln(), (e + e * e).ln(), 2.0]).unwrap()],
                tangent_outputs = [Array::vector(vec![
                    (1.0 + 2.0 * e + 3.0 * e * e) / (1.0 + e + e * e),
                    (2.0 * e + 3.0 * e * e) / (e + e * e),
                    3.0,
                ]).unwrap()],
            }],
        );
    }

    #[test]
    fn test_cumulative_log_sum_exp_capability_over_eager_arrays() {
        // The capability is the receiver-style entry point of the same kernel, in both scan directions, and it
        // reports the operation's own validation errors instead of panicking.
        let input = Array::vector(vec![0.0, 0.0]).unwrap();
        assert_eq!(input.cumulative_log_sum_exp(0), Ok(Array::vector(vec![0.0, std::f64::consts::LN_2]).unwrap()));
        assert_eq!(
            input.reverse_cumulative_log_sum_exp(0),
            Ok(Array::vector(vec![std::f64::consts::LN_2, 0.0]).unwrap())
        );
        assert_eq!(
            Array::vector(vec![1_i32, 2]).unwrap().cumulative_log_sum_exp(0),
            Err(ProgramError::Type(TypeError::invalid(
                "`cumulative_log_sum_exp` requires real floating-point inputs but got `i32`".to_string(),
            ))),
        );
    }
}
