//! Contains the [`CumulativeMinOperation`], the running-minimum member of the cumulative family, together with the
//! [`CumulativeMin`] staging capability and every rule the member does not choose for itself, all generated by
//! `define_cumulative_operation!`.

// TODO(eaplatanios): Review this module.

use std::fmt::Display;

use crate::arrays::{ArrayBatch, ArrayBatching, ArrayType, RaggedArrayBatchingPolicy, RaggedMaskIdentity};
use crate::batching::{
    BatchAxis, BatchableOperation, BatchedOutputs, BatchingContext, BatchingDriver, BatchingError,
    InterpretableBatchableOperation,
};
use crate::contexts::{Context, Domain};
use crate::differentiation::{
    DifferentiableOperation, DifferentiableType, DifferentiationDriver, DifferentiationDual, DifferentiationError,
};
use crate::interpretation::{InterpretableOperation, InterpretationDriver};
use crate::macros::{check_count, impl_non_transposable_operation};
use crate::operations::constants::zero::ZeroOperationProvider;
use crate::operations::cumulative::{
    cumulative_abstract, define_cumulative_operation, jvp_through_associative_scan, lift_cumulative_axis,
};
use crate::operations::manipulation::concatenation::ConcatenateOperation;
use crate::operations::manipulation::padding::PadOperation;
use crate::operations::manipulation::slicing::SliceOperation;
use crate::operations::math::add::AddOperation;
use crate::operations::math::min::{Min, MinOperation};
use crate::partial::PartiallyEvaluatableOperation;
use crate::programs::{
    MaybeZero, Operation, OperationFormatter, ProgramError, RegionInterface, TypeError, Typed, Value,
};

define_cumulative_operation! {
    /// Primitive representing one inclusive running minimum along a single array axis.
    ///
    /// Output element `i` along [`axis`](Self::axis) holds the minimum of input elements `0..=i`, or the minimum of
    /// elements `i..` when [`reverse`](Self::reverse) is set. The output type is the input type, so a
    /// `cumulative_min` is a shape-preserving unary primitive.
    ///
    /// The identity of the combining operator is the element data type's highest value (positive infinity for the
    /// floating-point formats that have infinities), which is what a batching rule writes over the padding of a
    /// bounded ragged scanned axis so that padded positions can never win a live prefix.
    ///
    /// The scanned dimension must be static and unsharded, as documented on [`cumulative_abstract`]. The element data
    /// type must be real numeric: complex numbers are unordered and therefore have no minimum, matching the
    /// elementwise [`Min`] operation. Exceptional values follow that operation too: NaNs propagate and `-0.0` orders
    /// below `+0.0`.
    operation = CumulativeMinOperation,
    name = CUMULATIVE_MIN_OPERATION_NAME = "cumulative_min",
    abstract_rule = cumulative_min_abstract,
    element_domain = |data_type| data_type.is_real(),
    element_domain_error = format!(
        "`{CUMULATIVE_MIN_OPERATION_NAME}` requires real numeric inputs but got {data_type}"
    ),
    ragged_identity = RaggedMaskIdentity::Highest,
    combine_operation = MinOperation<ArrayType>,
    combine = |left, right| left.min(right),
    /// Value-level cumulative minimum capability.
    ///
    /// [`CumulativeMin`] is the receiver-style entry point for staging or executing a [`CumulativeMinOperation`]: it
    /// scans the receiver along `axis`, returning a value of the receiver's own type whose element `i` along that
    /// axis holds the minimum of the receiver's elements `0..=i` (or `i..` for the reverse direction).
    capability = CumulativeMin::{cumulative_min, reverse_cumulative_min},
}

#[cfg(test)]
mod tests {
    use indoc::indoc;
    use pretty_assertions::assert_eq;

    use crate::arrays::batching::DynamicArrayBatchingPolicy;
    use crate::arrays::{
        Array, ArrayIrOperation, ArrayIrValue, DataType, Dimension, DimensionBounds, DimensionType, DimensionVariable,
        LogicalMesh, MeshAxis, MeshAxisType, RaggedAxis, Shape, Sharding, ShardingDimension,
    };
    use crate::contexts::{EagerContext, ProjectedContext, StagingContext};
    use crate::macros::{check_operation_batching, check_operation_differentiation};
    use crate::parameters::Placeholder;
    use crate::programs::{EmptyRegionDriver, ValueProjection};
    use crate::tracing::TracingContext;

    use super::*;

    #[test]
    fn test_cumulative_min_operation_type_inference() {
        // The output type follows the staged input type exactly.
        let operation = CumulativeMinOperation::new(1);
        let input = ArrayType::new_static(DataType::F64, [3, 2]);
        assert_eq!(operation.infer_output_types(std::slice::from_ref(&input), &[]), Ok(vec![input]));
        let integer = ArrayType::new_static(DataType::I32, [3, 2]);
        assert_eq!(operation.infer_output_types(std::slice::from_ref(&integer), &[]), Ok(vec![integer]));

        // Complex numbers are unordered and Booleans are not numeric, so neither has a running minimum.
        for data_type in [DataType::C64, DataType::Boolean, DataType::Token, DataType::Zero] {
            assert_eq!(
                operation.infer_output_types(&[ArrayType::new_static(data_type, [3, 2])], &[]),
                Err(TypeError::invalid(format!("`cumulative_min` requires real numeric inputs but got {data_type}"))),
            );
        }

        // The geometry rules of the family are enforced against the staged input type.
        assert_eq!(
            operation.infer_output_types(&[ArrayType::new_static(DataType::F64, [3])], &[]),
            Err(TypeError::invalid("`cumulative_min` axis 1 is out of bounds for rank 1".to_string())),
        );
        let dynamic = ArrayType::new(
            DataType::F64,
            Shape::new(vec![
                Dimension::Static(3),
                Dimension::Dynamic(DimensionVariable::new("length", DimensionBounds::new(0, Some(4)).unwrap())),
            ]),
        );
        assert_eq!(
            operation.infer_output_types(std::slice::from_ref(&dynamic), &[]),
            Err(TypeError::invalid(format!(
                "`cumulative_min` requires a static scanned dimension but axis 1 of {dynamic} is dynamic"
            ))),
        );
        let mesh = LogicalMesh::new(vec![MeshAxis::new("x", 2, MeshAxisType::Explicit).unwrap()]).unwrap();
        let sharded = ArrayType::new_static(DataType::F64, [3, 2])
            .with_sharding(
                Sharding::new(mesh, vec![ShardingDimension::replicated(), ShardingDimension::sharded(["x"])]).unwrap(),
            )
            .unwrap();
        assert_eq!(
            operation.infer_output_types(std::slice::from_ref(&sharded), &[]),
            Err(TypeError::invalid(format!(
                "`cumulative_min` requires an unsharded scanned dimension but axis 1 of {sharded} is sharded"
            ))),
        );
    }

    #[test]
    fn test_cumulative_min_operation_rendering() {
        // The scan direction renders only when it is set, keeping the common forward scan compact.
        assert_eq!(CumulativeMinOperation::new(1).to_string(), "cumulative_min [axis=1]");
        assert_eq!(
            CumulativeMinOperation::new(0).with_reverse(true).to_string(),
            "cumulative_min [axis=0, reverse=true]",
        );
        assert_eq!(CumulativeMinOperation::new(0).with_reverse(false), CumulativeMinOperation::new(0));
    }

    #[test]
    fn test_cumulative_min_operation_interpretation() {
        let context = EagerContext::<Array>::new();
        let interpret = |operation: &CumulativeMinOperation, input: &Array| {
            operation.interpret(&context, &EmptyRegionDriver, std::slice::from_ref(input)).unwrap().remove(0)
        };

        // Forward scans accumulate prefixes and reverse scans accumulate suffixes, along the selected axis only.
        let input = Array::matrix(2, 3, vec![3.0, 1.0, 4.0, 1.0, 5.0, 9.0]);
        assert_eq!(
            interpret(&CumulativeMinOperation::new(1), &input),
            Array::matrix(2, 3, vec![3.0, 1.0, 1.0, 1.0, 1.0, 1.0]),
        );
        assert_eq!(
            interpret(&CumulativeMinOperation::new(1).with_reverse(true), &input),
            Array::matrix(2, 3, vec![1.0, 1.0, 4.0, 1.0, 5.0, 9.0]),
        );
        assert_eq!(
            interpret(&CumulativeMinOperation::new(0), &input),
            Array::matrix(2, 3, vec![3.0, 1.0, 4.0, 1.0, 1.0, 4.0]),
        );

        // A monotonically ordered operand pins the two directions against each other: a descending sequence is its
        // own forward running minimum, and an ascending one is its own reverse running minimum.
        let ascending = Array::vector(vec![1.0, 2.0, 3.0, 4.0, 5.0]);
        assert_eq!(interpret(&CumulativeMinOperation::new(0), &ascending), Array::vector(vec![1.0; 5]));
        assert_eq!(interpret(&CumulativeMinOperation::new(0).with_reverse(true), &ascending), ascending.clone(),);
        let descending = Array::vector(vec![5.0, 4.0, 3.0, 2.0, 1.0]);
        assert_eq!(interpret(&CumulativeMinOperation::new(0), &descending), descending.clone());
        assert_eq!(
            interpret(&CumulativeMinOperation::new(0).with_reverse(true), &descending),
            Array::vector(vec![1.0; 5]),
        );

        // Integer payloads select in their own element type, and a zero-length scanned axis keeps the exact operand.
        assert_eq!(
            interpret(&CumulativeMinOperation::new(0), &Array::vector(vec![7_i32, -2, 3])),
            Array::vector(vec![7_i32, -2, -2]),
        );
        let empty = Array::new(ArrayType::new_static(DataType::F32, [0, 2]), Vec::new()).unwrap();
        assert_eq!(interpret(&CumulativeMinOperation::new(0), &empty), empty);

        // NaNs propagate through the elementwise extremum, so every later prefix of a NaN is NaN.
        let scanned = interpret(&CumulativeMinOperation::new(0), &Array::vector(vec![1.0, f64::NAN, 2.0]));
        let values = scanned.to_f64s();
        assert_eq!(values[0], 1.0);
        assert!(values[1].is_nan());
        assert!(values[2].is_nan());
    }

    #[test]
    fn test_cumulative_min_capability_over_eager_arrays() {
        // The capability is the receiver-style entry point of the same kernel, in both scan directions, and it
        // reports the operation's own validation errors instead of panicking.
        let input = Array::vector(vec![3.0, 1.0, 4.0]);
        assert_eq!(input.cumulative_min(0), Ok(Array::vector(vec![3.0, 1.0, 1.0])));
        assert_eq!(input.reverse_cumulative_min(0), Ok(Array::vector(vec![1.0, 1.0, 4.0])));
        assert_eq!(
            input.cumulative_min(1),
            Err(ProgramError::Type(TypeError::invalid(
                "`cumulative_min` axis 1 is out of bounds for rank 1".to_string(),
            ))),
        );
    }

    #[test]
    fn test_cumulative_min_operation_batches_along_the_shifted_axis() {
        // A replicated operand carries no inserted batch dimension, so the scanned axis needs no shift.
        check_operation_batching!(
            @exact,
            operation = CumulativeMinOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@replicated, Array::vector(vec![3.0, 1.0, 4.0]))],
                outputs = [(@replicated, Array::vector(vec![3.0, 1.0, 1.0]))],
            }],
        );

        // Physical input is [2 batch items, 3 columns] mapped at axis 0, so the per-item axis 0 scans physical axis
        // 1 and each batch item accumulates independently.
        check_operation_batching!(
            @exact,
            operation = CumulativeMinOperation::new(0),
            axis_size = 2,
            cases = [{
                inputs = [(@mapped(axis = 0), Array::matrix(2, 3, vec![3.0, 1.0, 4.0, 1.0, 5.0, 9.0]))],
                outputs = [(@mapped(axis = 0), Array::matrix(2, 3, vec![3.0, 1.0, 1.0, 1.0, 1.0, 1.0]))],
            }],
        );

        // With the batch dimension inserted after the scanned axis, the scanned axis keeps its position.
        check_operation_batching!(
            @exact,
            operation = CumulativeMinOperation::new(0),
            axis_size = 3,
            cases = [{
                inputs = [(@mapped(axis = 1), Array::matrix(2, 3, vec![3.0, 1.0, 4.0, 1.0, 5.0, 9.0]))],
                outputs = [(@mapped(axis = 1), Array::matrix(2, 3, vec![3.0, 1.0, 4.0, 1.0, 1.0, 4.0]))],
            }],
        );
    }

    #[test]
    fn test_cumulative_min_operation_masks_ragged_padding_with_the_highest_value() {
        // Scanning a ragged axis would let its padding win every later live prefix, so the rule asks the policy to
        // neutralize that padding with the highest representable value first. Static array batching cannot, and says
        // so rather than silently scanning padding.
        let variable = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let input = ArrayBatch::new(Array::matrix(2, 3, vec![1.0_f32; 6]), BatchAxis::new(0))
            .unwrap()
            .with_ragged_axes(vec![RaggedAxis::new(1, Array::vector(vec![1_i32, 3]), variable, vec![0])])
            .unwrap();
        assert_eq!(
            CumulativeMinOperation::new(0).batch(
                &BatchingContext::new(EagerContext::<Array>::new(), 2),
                &EmptyRegionDriver,
                &[input],
            ),
            Err(BatchingError::UnsupportedOperation {
                message: "static array batching cannot identity-mask bounded ragged axes".to_string(),
            }),
        );

        // The composite dynamic policy can, and stages the mask ahead of the scan: the padded positions of the
        // scanned axis are selected away in favor of positive infinity, and the ragged axis survives on the result
        // because a scan consumes no axis.
        type TraceContext = TracingContext<ArrayIrValue<Array>, ArrayIrOperation<Array>>;
        let trace = TraceContext::new();
        let items = DimensionVariable::new("items", DimensionBounds::new(1, Some(9)).unwrap());
        let length = DimensionVariable::new("length", DimensionBounds::new(0, Some(3)).unwrap());
        let batch_extent = trace.input(DimensionType::new(items.clone()).into());
        let packed = trace.input(
            ArrayType::new(DataType::F32, Shape::new(vec![Dimension::Dynamic(items.clone()), Dimension::Static(3)]))
                .into(),
        );
        let extents = trace.input(ArrayType::new(DataType::I32, Shape::new(vec![Dimension::Dynamic(items)])).into());
        let context = BatchingContext::<_, ArrayBatching<DynamicArrayBatchingPolicy>>::with_policy(
            ProjectedContext::new(trace.clone()),
            batch_extent,
        );
        let input = ArrayBatch::new(packed.into_projected().unwrap(), BatchAxis::new(0))
            .unwrap()
            .with_ragged_axes(vec![RaggedAxis::new(1, extents.into_projected().unwrap(), length.clone(), vec![0])])
            .unwrap();
        // The per-item scan of axis 0 is the packed axis 1 that carries the ragged extents.
        let (outputs, evidence) =
            CumulativeMinOperation::new(0).batch(&context, &EmptyRegionDriver, &[input]).unwrap().into_parts();
        assert_eq!(outputs.len(), 1);
        assert_eq!(outputs[0].batch_axis(), BatchAxis::new(0));
        assert_eq!(outputs[0].ragged_axes().len(), 1);
        assert_eq!(outputs[0].ragged_axes()[0].axis(), 1);
        assert_eq!(outputs[0].ragged_axes()[0].dimension(), &length);
        assert!(evidence.is_empty());

        let output_id = outputs.into_iter().next().unwrap().into_value().into_value().atom_id().unwrap();
        drop(context);
        let program = trace
            .builder()
            .borrow()
            .clone()
            .build::<Vec<ArrayIrValue<Array>>, Vec<ArrayIrValue<Array>>>(
                vec![output_id],
                vec![Placeholder, Placeholder, Placeholder],
                vec![Placeholder],
            )
            .unwrap();
        assert_eq!(
            program.to_string(),
            indoc! {"
                lambda %0:dimension<items ∈ [1, 9)>, %1:f32[items, 3], %2:i32[items] .
                let %3:dimension<items ∈ [1, 9)> = dimension_size [axis=0] %1
                    %4:dimension<3> = constant [value=3]
                    %5:i32[3] = iota [type=i32[3], dimension=0]
                    %6:i32[items, 3] = broadcast [output_axes=[1]] %5 %3 %4
                    %7:i32[items, 3] = broadcast [output_axes=[0]] %2 %3 %4
                    %8:bool[items, 3] = compare [direction=LessThan] %6 %7
                    %9:f32[] = constant [value=inf]
                    %10:f32[items, 3] = broadcast [output_axes=[]] %9 %3 %4
                    %11:f32[items, 3] = select %8 %1 %10
                    %12:f32[items, 3] = cumulative_min [axis=1] %11
                in (%12)
            "}
            .trim_end(),
        );
    }

    #[test]
    fn test_cumulative_min_operation_differentiation() {
        // At tie-free inputs the derivative of a running minimum routes each output's tangent from the element that
        // currently attains the minimum, which is what folding the elementwise minimum's own rule produces.
        check_operation_differentiation!(
            @approx(step = 1e-3, epsilon = 1e-6),
            operation = CumulativeMinOperation::new(0),
            cases = [{
                primals = [Array::vector(vec![3.0, 1.0, 4.0, 1.5, 5.0])],
                tangents = [Array::vector(vec![1.0, 2.0, 3.0, 4.0, 5.0])],
                primal_outputs = [Array::vector(vec![3.0, 1.0, 1.0, 1.0, 1.0])],
                tangent_outputs = [Array::vector(vec![1.0, 2.0, 2.0, 2.0, 2.0])],
            }],
        );
        check_operation_differentiation!(
            @approx(step = 1e-3, epsilon = 1e-6),
            operation = CumulativeMinOperation::new(0).with_reverse(true),
            cases = [{
                primals = [Array::vector(vec![3.0, 1.0, 4.0, 1.5, 5.0])],
                tangents = [Array::vector(vec![1.0, 2.0, 3.0, 4.0, 5.0])],
                primal_outputs = [Array::vector(vec![1.0, 1.0, 1.5, 1.5, 5.0])],
                tangent_outputs = [Array::vector(vec![2.0, 2.0, 4.0, 4.0, 5.0])],
            }],
        );
    }
}
