[package]
name = "ryft-experimental"
version = "0.1.0"
readme = "README.md"
publish = false

authors.workspace = true
edition.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
ryft-cuda = { workspace = true, optional = true }
ryft-triton = { workspace = true, optional = true }
ryft-pjrt.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
ryft-core.workspace = true
ryft-mlir.workspace = true
ryft-mosaic.workspace = true
ryft-xla.workspace = true
ryft-xla-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[features]
triton = ["dep:ryft-triton", "ryft-xla/triton"]
cutile = ["dep:ryft-cuda", "ryft-cuda/cutile-compiler", "ryft-xla/cutile-compiler"]
default = []
cuda-12 = ["dep:ryft-cuda", "ryft-pjrt/cuda-12", "ryft-xla/cuda-12"]
cuda-13 = ["dep:ryft-cuda", "ryft-pjrt/cuda-13", "ryft-xla/cuda-13"]
mosaic-gpu = ["ryft-xla/mosaic-gpu"]
