use std::fmt::Display;

use proc_macro2::TokenStream;
use quote::{ToTokens, quote};
use syn::visit_mut::VisitMut;

use crate::helpers::attributes::Attribute;
use crate::helpers::generics::GenericsHelpers;
use crate::helpers::hygiene::const_block;
use crate::helpers::receivers::replace_self_type;
use crate::helpers::symbols::Symbol;

const RYFT_ATTRIBUTE: Symbol = Symbol::new("ryft");
const CRATE_ATTRIBUTE: Symbol = Symbol::new("crate");
const DISPATCH_ATTRIBUTE: Symbol = Symbol::new("dispatch");
const BATCHING_ATTRIBUTE: Symbol = Symbol::new("batching");
const DIFFERENTIATION_ATTRIBUTE: Symbol = Symbol::new("differentiation");
const TRANSPOSITION_ATTRIBUTE: Symbol = Symbol::new("transposition");
const VALID_CONTAINER_ATTRIBUTES: [Symbol; 2] = [CRATE_ATTRIBUTE, DISPATCH_ATTRIBUTE];

const DEFAULT_RYFT_CRATE: Symbol = Symbol::new("ryft");
const NESTED_ATTRIBUTE_ERROR: &str = "\
  the '#[ryft(...)]' attribute is only supported at the top level for operation enums. It is not supported for \
  variants or fields";

/// Mutable parser and diagnostic accumulator for `#[derive(Operation)]`.
struct OperationParser {
    /// Path to the `ryft` crate or facade used by generated code.
    ryft_crate: syn::Path,

    /// Type descriptor for the generated [`Operation`](ryft_core::Operation) implementation.
    operation_type: Option<syn::Type>,

    /// Optional operation dispatchers selected through `#[ryft(dispatch(...))]`.
    dispatchers: Option<Dispatchers>,

    /// Errors accumulated in this [`OperationParser`]. The way error handling works in this parser is that we
    /// collect errors as we encounter them, and keep going as far as we can with the information that is available,
    /// before raising them. That is meant to enable a smoother development experience when working with `ryft` by
    /// reducing the amount of trial and error required to get something work (i.e., users do not need to keep trying,
    /// fixing one error at a time; they get to see multiple errors at once, when there are multiple).
    errors: Vec<syn::Error>,
}

/// Optional dispatchers generated by `#[derive(Operation)]`.
#[derive(Copy, Clone, Default)]
struct Dispatchers {
    /// Whether to generate the batching dispatcher.
    batching: bool,

    /// Whether to generate the differentiation dispatcher.
    differentiation: bool,

    /// Whether to generate the transposition dispatcher.
    transposition: bool,
}

/// Normalized operation enum shared by every generated dispatcher.
struct OperationEnum {
    /// Path to the `ryft` crate or facade used by generated code.
    ryft_crate: syn::Path,

    /// Type descriptor for the generated [`Operation`](ryft_core::Operation) implementation.
    operation_type: syn::Type,

    /// Optional operation dispatchers selected through `#[ryft(dispatch(...))]`.
    dispatchers: Dispatchers,

    /// Enum identifier.
    ident: syn::Ident,

    /// Original enum generics after recursive `Self` replacement.
    generics: syn::Generics,

    /// Enum generics without defaults, used by conversion implementations.
    conversion_generics: syn::Generics,

    /// Enum generics with generic-extension operation bounds, used by semantic implementations.
    operation_generics: syn::Generics,

    /// Enum self type using all declared generic arguments.
    self_type: syn::Type,

    /// Whether the enum has exactly one parameter bounded by `Value<Type = T>`.
    has_single_value_parameter: bool,

    /// First value parameter, which represents program constants.
    program_constant_type: syn::Ident,

    /// Program-shaped generics after reducing payload-specific value parameters to the program constant space.
    program_generics: syn::Generics,

    /// Program-shaped enum self type after reducing payload-specific value parameters to the program constant space.
    program_self_type: syn::Type,

    /// Normalized operation variants.
    variants: Vec<OperationVariant>,
}

/// Generates the `#[derive(Operation)]` expansion for `input`.
pub(crate) fn generate_operation_impl(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let mut input = syn::parse_macro_input!(input as syn::DeriveInput);
    replace_self_type(&mut input);

    let mut parser = OperationParser::new();
    parser.extract_attributes(&input);
    if parser.has_errors() {
        return parser.into_compile_error().into();
    }

    let Some(operation_enum) = parser.normalize_input(&input) else {
        return parser.into_compile_error().into();
    };
    operation_enum.generate().into()
}

impl OperationParser {
    /// Creates a new [`OperationParser`] with default parser state.
    fn new() -> Self {
        OperationParser {
            ryft_crate: DEFAULT_RYFT_CRATE.into(),
            operation_type: None,
            dispatchers: None,
            errors: Vec::new(),
        }
    }

    /// Adds an error to this [`OperationParser`] with the specified message spanning the provided tokens. This is only
    /// meant to be used internally by this class as a convenient helper for collecting errors.
    ///
    /// # Parameters
    ///
    ///   * `tokens` - Tokens that the error spans.
    ///   * `message` - Message describing the error.
    fn add_error<T: ToTokens, U: Display>(&mut self, tokens: T, message: U) {
        self.errors.push(syn::Error::new_spanned(tokens.into_token_stream(), message));
    }

    /// Returns whether any diagnostics have been accumulated.
    fn has_errors(&self) -> bool {
        !self.errors.is_empty()
    }

    /// Combines all accumulated diagnostics into one `compile_error!` token stream.
    ///
    /// This method is called only after [`OperationParser::has_errors`] returns `true` or normalization returns
    /// [`None`], which always adds at least one diagnostic.
    fn into_compile_error(self) -> TokenStream {
        let mut errors = self.errors.into_iter();
        let mut error = errors.next().unwrap();
        for next_error in errors {
            error.combine(next_error);
        }
        error.into_compile_error()
    }

    /// Extracts any `#[ryft(...)]` attributes that are attached to the provided [`syn::DeriveInput`] and checks for
    /// unknown top-level (i.e., not field or variant) `#[ryft(...)]` attributes. This function will set
    /// [`OperationParser::ryft_crate`] and [`OperationParser::dispatchers`] if it is able to successfully extract them,
    /// and it also infers [`OperationParser::operation_type`] from the enum's `Value<Type = T>` generic bounds (there
    /// must be exactly one distinct such bound argument and an error is generated if there are zero or more than one).
    fn extract_attributes(&mut self, input: &syn::DeriveInput) {
        let mut ryft_crate = Attribute::new(CRATE_ATTRIBUTE);
        input.attrs.iter().filter(|attr| attr.path() == &RYFT_ATTRIBUTE).for_each(|attr| {
            attr.parse_nested_meta(|meta| match &meta.path {
                path if path == &CRATE_ATTRIBUTE => ryft_crate.set(&meta),
                path if path == &DISPATCH_ATTRIBUTE => self.extract_dispatch_attribute(&meta),
                _ => Err(meta.error(format_args!(
                    "invalid '#[ryft(...)]' attribute: '{}'; these are the attributes that are supported here: {:?}",
                    meta.path.to_token_stream().to_string().replace(' ', ""),
                    VALID_CONTAINER_ATTRIBUTES,
                ))),
            })
            .unwrap_or_else(|error| self.errors.push(error));
        });

        if let Some(ryft_crate) = ryft_crate.get() {
            self.ryft_crate = ryft_crate;
        }
        let inferred_types = unique_value_bound_arguments(&input.generics);
        match inferred_types.as_slice() {
            [operation_type] => self.operation_type = Some(operation_type.clone()),
            [] => self.add_error(
                &input.ident,
                "could not infer an operation type because no generic parameter is bounded by 'Value<Type = T>'",
            ),
            _ => self.add_error(
                &input.generics,
                "could not infer a unique operation type because multiple distinct 'Value<Type = T>' bounds are present",
            ),
        }
    }

    /// Extracts the optional dispatchers selected by a `#[ryft(dispatch(...))]` attribute.
    fn extract_dispatch_attribute(&mut self, meta: &syn::meta::ParseNestedMeta) -> syn::Result<()> {
        if self.dispatchers.is_some() {
            return Err(meta.error("duplicate ryft attribute 'dispatch(...)'"));
        }

        let content;
        syn::parenthesized!(content in meta.input);
        if content.is_empty() {
            return Err(content.error("'#[ryft(dispatch(...))]' must select at least one dispatcher"));
        }
        let dispatchers = syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated(&content)?;
        let mut selected_dispatchers = Dispatchers::default();
        for dispatcher in dispatchers {
            let selected = match &dispatcher {
                path if path == &BATCHING_ATTRIBUTE => &mut selected_dispatchers.batching,
                path if path == &DIFFERENTIATION_ATTRIBUTE => &mut selected_dispatchers.differentiation,
                path if path == &TRANSPOSITION_ATTRIBUTE => &mut selected_dispatchers.transposition,
                _ => {
                    return Err(syn::Error::new_spanned(
                        &dispatcher,
                        format_args!(
                            "invalid '#[ryft(dispatch(...))]' dispatcher: '{}'; only 'batching', 'differentiation', and \
                         'transposition' are supported here",
                            dispatcher.to_token_stream().to_string().replace(' ', ""),
                        ),
                    ));
                }
            };
            if *selected {
                return Err(syn::Error::new_spanned(
                    &dispatcher,
                    format_args!(
                        "duplicate ryft dispatcher '{}'",
                        dispatcher.to_token_stream().to_string().replace(' ', ""),
                    ),
                ));
            }
            *selected = true;
        }
        self.dispatchers = Some(selected_dispatchers);
        Ok(())
    }

    /// Extracts the [`OperationVariant`]s that are contained in the provided [`syn::DeriveInput`]. This function
    /// also checks that the input is an enum, because the operation derives do not support structs or unions.
    fn extract_variants(&mut self, input: &syn::DeriveInput) -> Vec<OperationVariant> {
        let syn::Data::Enum(data) = &input.data else {
            self.add_error(&input.ident, "the '#[derive(Operation)]' macro only supports enums");
            return Vec::new();
        };

        data.variants.iter().filter_map(|variant| self.extract_variant(&input.generics, variant)).collect()
    }

    /// Normalizes the enum metadata shared by all generated implementations.
    fn normalize_input(&mut self, input: &syn::DeriveInput) -> Option<OperationEnum> {
        let variants = self.extract_variants(input);
        if self.has_errors() {
            return None;
        }

        let operation_type = self.operation_type.clone()?;

        let ident = input.ident.clone();
        let generics = input.generics.clone();
        let conversion_generics = generics.without_defaults();
        let (_, type_generics, _) = conversion_generics.split_for_impl();
        let self_type: syn::Type = syn::parse_quote!(#ident #type_generics);
        let value_type_parameters = value_type_parameters(&generics, &operation_type);
        let Some(program_constant_type) = value_type_parameters.first().cloned() else {
            self.add_error(&generics, "could not infer the program constant value type for '#[derive(Operation)]'");
            return None;
        };
        let program_value_substitutions = program_value_substitutions(&value_type_parameters, &program_constant_type);
        let program_self_type = substitute_type_idents(&self_type, &program_value_substitutions);
        let operation_generics = operation_generics(&generics, &variants, &self.ryft_crate, &operation_type);
        let program_generics = substitute_generics(&operation_generics, &program_value_substitutions);
        let variants = variants
            .into_iter()
            .map(|mut variant| {
                variant.program_payload_type =
                    substitute_type_idents(&variant.payload_type, &program_value_substitutions);
                variant
            })
            .collect();

        Some(OperationEnum {
            ryft_crate: self.ryft_crate.clone(),
            operation_type,
            dispatchers: self.dispatchers.unwrap_or_default(),
            ident,
            generics,
            conversion_generics,
            operation_generics,
            self_type,
            has_single_value_parameter: value_type_parameters.len() == 1,
            program_constant_type,
            program_generics,
            program_self_type,
            variants,
        })
    }

    /// Extracts one [`OperationVariant`] from the provided [`syn::Variant`]. This function also checks that the
    /// variant is a tuple variant with exactly one payload field and rejects nested `#[ryft(...)]` attributes on
    /// that field.
    ///
    /// # Parameters
    ///
    ///   * `enum_name` - [`syn::Ident`] of the enum being derived, used to detect recursive payloads.
    ///   * `generics` - [`syn::Generics`] of the enum being derived, used to detect bare generic payloads.
    ///   * `variant` - [`syn::Variant`] from which to extract an [`OperationVariant`].
    fn extract_variant(&mut self, generics: &syn::Generics, variant: &syn::Variant) -> Option<OperationVariant> {
        self.reject_nested_attributes(&variant.attrs);
        let syn::Fields::Unnamed(fields) = &variant.fields else {
            self.add_error(&variant.ident, "operation enum variants must be tuple variants with one payload field");
            return None;
        };
        if fields.unnamed.len() != 1 {
            self.add_error(&variant.fields, "operation enum variants must have exactly one payload field");
            return None;
        }
        let field = fields.unnamed.first().expect("expected one payload field");
        self.reject_nested_attributes(&field.attrs);

        let payload_type = field.ty.clone();
        let (operation_type, is_boxed) = boxed_inner_type(&payload_type)
            .map(|operation_type| (operation_type, true))
            .unwrap_or_else(|| (payload_type.clone(), false));
        let is_generic_extension = is_bare_generic_parameter(&payload_type, generics);

        Some(OperationVariant {
            ident: variant.ident.clone(),
            program_payload_type: operation_type.clone(),
            payload_type: operation_type,
            is_boxed,
            is_generic_extension,
        })
    }

    /// Rejects nested `#[ryft(...)]` attributes, which are only supported at the top level for operation enums and
    /// never on variants or payload fields.
    fn reject_nested_attributes(&mut self, attributes: &[syn::Attribute]) {
        attributes
            .iter()
            .filter(|attr| attr.path() == &RYFT_ATTRIBUTE)
            .for_each(|attr| self.add_error(attr, NESTED_ATTRIBUTE_ERROR));
    }
}

impl OperationEnum {
    /// Generates every semantic implementation selected for this operation enum.
    fn generate(&self) -> TokenStream {
        let operation = self.generate_operation();
        let batching = self.dispatchers.batching.then(|| self.generate_batchable_operation());
        let differentiation = self.dispatchers.differentiation.then(|| self.generate_differentiable_operation());
        let transposition = self.dispatchers.transposition.then(|| self.generate_transposable_operation());
        quote!(#operation #batching #differentiation #transposition)
    }

    /// Generates the `Operation` derive output: the [`Operation`] dispatcher, the [`InterpretableOperation`]
    /// dispatcher, the
    /// [`PartiallyEvaluatableOperation`] dispatcher, the [`Display`] implementation, and the `From` and borrowed
    /// `TryFrom` payload conversions. Refer to the documentation of the [`Operation`] trait for information on the
    /// shape of the generated code and on how the interpretation value types are inferred from the enum's
    /// `Value<Type = T>` generic parameters.
    fn generate_operation(&self) -> TokenStream {
        let variants = &self.variants;
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;

        let operation_self_type = &self.self_type;
        let operation_generics = &self.operation_generics;
        let (operation_impl_generics, _, operation_where_clause) = operation_generics.split_for_impl();
        let operation = self.generate_operation_dispatcher();
        let interpretation = self.generate_interpretable_operation();
        let partial_evaluation = self.generate_partially_evaluatable_operation();
        let conversion_impls = variants
            .iter()
            .filter(|variant| !variant.is_generic_extension)
            .map(|variant| self.generate_conversion_impl(variant));

        const_block(quote! {
            #operation

            #interpretation

            #partial_evaluation

            #[automatically_derived]
            impl #operation_impl_generics ::std::fmt::Display for #operation_self_type
            #operation_where_clause
            {
                fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                    <Self as #ryft::Operation<#primary_type>>::render(self, formatter, 0)
                }
            }

            #(#conversion_impls)*
        })
    }

    /// Generates the base [`Operation`] dispatcher.
    fn generate_operation_dispatcher(&self) -> TokenStream {
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;
        let operation_self_type = &self.self_type;
        let (impl_generics, _, where_clause) = self.operation_generics.split_for_impl();
        let name_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::name(#receiver)
                },
            }
        });
        let infer_output_type_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::infer_output_types(
                        #receiver,
                        input_types,
                        region_interfaces,
                    )
                },
            }
        });
        let region_name_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::region_names(#receiver)
                },
            }
        });
        let provenance_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::output_region_provenance(
                        #receiver,
                        output_index,
                    )
                },
            }
        });
        let is_zero_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::is_zero(#receiver, output_index)
                },
            }
        });
        let effects_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::effects(#receiver)
                },
            }
        });
        let render_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_type as #ryft::Operation<#primary_type>>::render(#receiver, formatter, indentation)
                },
            }
        });

        quote! {
            #[automatically_derived]
            impl #impl_generics #ryft::Operation<#primary_type> for #operation_self_type
            #where_clause
            {
                fn name(&self) -> &'static str {
                    match self { #(#name_arms)* }
                }

                fn infer_output_types(
                    &self,
                    input_types: &[#primary_type],
                    region_interfaces: &[#ryft::RegionInterface<#primary_type>],
                ) -> ::std::result::Result<::std::vec::Vec<#primary_type>, #ryft::TypeError> {
                    match self { #(#infer_output_type_arms)* }
                }

                fn region_names(&self) -> &'static [&'static str] {
                    match self { #(#region_name_arms)* }
                }

                fn output_region_provenance(
                    &self,
                    output_index: usize,
                ) -> ::std::vec::Vec<#ryft::OutputRegionProvenance> {
                    match self { #(#provenance_arms)* }
                }

                fn is_zero(&self, output_index: usize) -> bool {
                    match self { #(#is_zero_arms)* }
                }

                fn effects(&self) -> #ryft::Effects {
                    match self { #(#effects_arms)* }
                }

                fn render(
                    &self,
                    formatter: &mut ::std::fmt::Formatter<'_>,
                    indentation: usize,
                ) -> ::std::fmt::Result {
                    match self { #(#render_arms)* }
                }
            }
        }
    }

    /// Generates the always-present [`InterpretableOperation`] dispatcher.
    fn generate_interpretable_operation(&self) -> TokenStream {
        let ryft = &self.ryft_crate;
        let interpretation_self_type = &self.program_self_type;
        let interpretation_generics = self.interpretation_generics();
        let (interpretation_impl_generics, _, interpretation_where_clause) = interpretation_generics.split_for_impl();
        let interpretation_arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let payload_operation_type = &variant.program_payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#payload_operation_type as #ryft::InterpretableOperation<__Context>>::interpret(
                        #receiver,
                        context,
                        driver,
                        inputs,
                    )
                },
            }
        });

        quote! {
            #[automatically_derived]
            impl #interpretation_impl_generics
                #ryft::InterpretableOperation<__Context>
                for #interpretation_self_type
            #interpretation_where_clause
            {
                fn interpret<__D: #ryft::InterpretationDriver<__Context>>(
                    &self,
                    context: &__Context,
                    driver: &__D,
                    inputs: &[<__Context as #ryft::Domain>::Value],
                ) -> ::std::result::Result<
                    ::std::vec::Vec<<__Context as #ryft::Domain>::Value>,
                    #ryft::ProgramError,
                > {
                    match self {
                        #(#interpretation_arms)*
                    }
                }
            }
        }
    }

    /// Generates the always-present [`PartiallyEvaluatableOperation`] dispatcher.
    fn generate_partially_evaluatable_operation(&self) -> TokenStream {
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;
        let partial_evaluation_self_type = &self.program_self_type;
        let partial_evaluation_value_type = &self.program_constant_type;
        let mut generics = self.program_generics.clone();
        generics.params.push(syn::parse_quote!(__Context));
        let where_clause = generics.make_where_clause();
        where_clause.predicates.push(syn::parse_quote! {
            __Context: #ryft::Context<
                Type = #primary_type,
                Constant = #partial_evaluation_value_type,
                Operation = #partial_evaluation_self_type,
            >
        });

        // Bare generic extension payloads residualize the complete enum operation instead of naming a payload rule.
        where_clause
            .predicates
            .extend(self.variants.iter().filter(|variant| !variant.is_generic_extension).map(|variant| {
                let operation_type = &variant.program_payload_type;
                let predicate: syn::WherePredicate = syn::parse_quote! {
                    #operation_type: #ryft::partial::PartiallyEvaluatableOperation<__Context>
                };
                predicate
            }));
        let arms = self.variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            if variant.is_generic_extension {
                quote! {
                    Self::#variant_ident(_) => {
                        let regions = driver
                            .regions()?
                            .into_iter()
                            .map(|region| region.to_program())
                            .collect();
                        context.fold_or_residualize(self.clone(), regions, inputs)
                    },
                }
            } else {
                let operation_type = &variant.program_payload_type;
                let receiver = variant.receiver();
                quote! {
                    Self::#variant_ident(operation) => {
                        <#operation_type as #ryft::partial::PartiallyEvaluatableOperation<__Context>>::
                            partially_evaluate(#receiver, context, driver, inputs)
                    },
                }
            }
        });
        let (impl_generics, _, where_clause) = generics.split_for_impl();

        quote! {
            #[automatically_derived]
            impl #impl_generics
                #ryft::partial::PartiallyEvaluatableOperation<__Context>
                for #partial_evaluation_self_type
            #where_clause
            {
                fn partially_evaluate<__D: #ryft::partial::PartialEvaluationDriver<__Context>>(
                    &self,
                    context: &#ryft::partial::PartialEvaluationContext<__Context>,
                    driver: &__D,
                    inputs: &[#ryft::partial::PartialEvaluationValue<
                        <__Context as #ryft::Domain>::Value,
                    >],
                ) -> ::std::result::Result<
                    ::std::vec::Vec<#ryft::partial::PartialEvaluationValue<
                        <__Context as #ryft::Domain>::Value,
                    >>,
                    #ryft::ProgramError,
                > {
                    match self {
                        #(#arms)*
                    }
                }
            }
        }
    }

    /// Generates the `BatchableOperation` derive output: one fixed-active-context `BatchableOperation` dispatcher.
    ///
    /// The generated dispatcher is generic over a `__ParentContext` parent context pinned to the enum's primary
    /// type, program constant type, and the enum itself as its operation family. Every variant forwards the active
    /// `BatchingContext<__ParentContext>` and instruction-scoped `BatchingDriver` to its payload's own rule. Ordinary
    /// rules execute their lifted work through `context.parent()`, while rules keyed on the active frame (e.g.,
    /// named-axis collectives) inspect its axis metadata directly. Each payload carries its batching obligation as a
    /// per-variant `BatchableOperation<__ParentContext>` predicate that transports the rule's own capability
    /// requirements to the use site, together with the parent `Zero` leaf that backs accumulator seeding. Nested
    /// programs batch structurally through
    /// `Program::batched`, requested by higher-order rules through their active driver, whose implementation
    /// establishes the finite program-level bounds at its construction site.
    fn generate_batchable_operation(&self) -> TokenStream {
        let variants = &self.variants;
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;
        let program_constant_type = &self.program_constant_type;
        let batching_self_type = &self.program_self_type;

        // Fixed-active-context dispatcher: every arm receives the active `BatchingContext<__ParentContext>`, the
        // current instruction's `BatchingDriver`, and the parent context's own value.
        let parent_value_type: syn::Type = syn::parse_quote!(<__ParentContext as #ryft::Domain>::Value);
        let mut batching_generics = self.program_generics.clone();
        batching_generics.params.push(syn::parse_quote!(__ParentContext));
        let batching_where_clause = batching_generics.make_where_clause();
        batching_where_clause.predicates.push(syn::parse_quote! {
            __ParentContext: #ryft::Context<
                Type = #primary_type,
                Constant = #program_constant_type,
                Operation = #batching_self_type,
            >
        });
        batching_where_clause.predicates.extend(variants.iter().map(|variant| {
            let operation_type = &variant.program_payload_type;
            let predicate: syn::WherePredicate =
                syn::parse_quote!(#operation_type: #ryft::BatchableOperation<__ParentContext>);
            predicate
        }));

        // Recursive higher-order rules seed accumulators through the parent context's `Zero` capability. All other
        // value requirements are transported by the per-payload batching predicates above.
        batching_where_clause
            .predicates
            .push(syn::parse_quote!(__ParentContext: #ryft::Zero<#parent_value_type>));
        let batching_arms = variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let operation_type = &variant.program_payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#operation_type as #ryft::BatchableOperation<__ParentContext>>::batch(
                        #receiver,
                        context,
                        driver,
                        inputs,
                    )
                },
            }
        });
        let (batching_impl_generics, _, batching_where_clause) = batching_generics.split_for_impl();
        const_block(quote! {
            #[automatically_derived]
            impl #batching_impl_generics #ryft::BatchableOperation<__ParentContext> for #batching_self_type
            #batching_where_clause
            {
                fn batch<__D: #ryft::BatchingDriver<__ParentContext>>(
                    &self,
                    context: &#ryft::BatchingContext<__ParentContext>,
                    driver: &__D,
                    inputs: &[#ryft::ArrayBatch<#parent_value_type>],
                ) -> ::std::result::Result<
                    ::std::vec::Vec<#ryft::ArrayBatch<#parent_value_type>>,
                    #ryft::BatchingError,
                > {
                    match self {
                        #(#batching_arms)*
                    }
                }
            }
        })
    }

    /// Generates the forward-mode (JVP) dispatcher of the `DifferentiableOperation` derive output.
    ///
    /// The generated implementation is generic over a `__DifferentiationContext` staging context pinned to the enum's
    /// primary type, program constant type, and the enum itself as its operation family. Every variant forwards to its
    /// payload's own `DifferentiableOperation` rule. Every payload carries a direct per-variant predicate that
    /// transports the rule's own capability requirements. Higher-order rules request nested differentiation through
    /// their instruction-scoped driver, whose concrete implementation establishes the finite `Program::jvp` and
    /// `Program::linearize` bounds at its construction site.
    fn generate_differentiable_operation(&self) -> TokenStream {
        let variants = &self.variants;
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;
        let program_constant_type = &self.program_constant_type;
        let differentiation_self_type = &self.program_self_type;
        let mut differentiation_generics = self.program_generics.clone();
        differentiation_generics.params.push(syn::parse_quote!(__DifferentiationContext));
        let where_clause = differentiation_generics.make_where_clause();
        where_clause.predicates.push(syn::parse_quote! {
            __DifferentiationContext: #ryft::Context<
                Type = #primary_type,
                Constant = #program_constant_type,
                Operation = #differentiation_self_type,
            >
        });
        // Higher-order payload rules materialize structural zero tangents at sub-program boundaries through the
        // context's `Zero` capability, so the dispatcher transports that requirement explicitly. Staging contexts
        // satisfy it through the blanket staging `Zero` implementation and eager domains implement it directly.
        where_clause.predicates.push(syn::parse_quote! {
            __DifferentiationContext: #ryft::Zero<<__DifferentiationContext as #ryft::Domain>::Value>
        });
        // The `while` rule concretizes data-dependent loop predicates on the carried values when the context is
        // eager, so the dispatcher also transports the `BooleanLike` value requirement. Staged values
        // satisfy it through the tracer `BooleanLike` implementation (whose `boolean` defers with an error) and
        // eager values implement it directly.
        where_clause.predicates.push(syn::parse_quote! {
            <__DifferentiationContext as #ryft::Domain>::Value: #ryft::BooleanLike
        });
        // The per-variant rules stage ordinary primal-enum operations for both the primal and the tangent side, so the
        // enum must offer the `From` conversion for every concrete payload. Bare generic payloads have no conversion
        // and instead carry their own forward-mode obligation directly.
        where_clause.predicates.extend(variants.iter().filter(|variant| !variant.is_generic_extension).map(
            |variant| {
                let operation_type = &variant.program_payload_type;
                let predicate: syn::WherePredicate =
                    syn::parse_quote!(#differentiation_self_type: ::std::convert::From<#operation_type>);
                predicate
            },
        ));
        // Every payload carries its forward-mode obligation as a per-variant predicate, exactly like the
        // interpretation and partial-evaluation impls. The predicate transports each rule's own capability
        // requirements (e.g., `C::Value: Sin` for the sine rule) to the use site without the enum spelling them.
        where_clause.predicates.extend(variants.iter().map(|variant| {
            let operation_type = &variant.program_payload_type;
            let predicate: syn::WherePredicate =
                syn::parse_quote!(#operation_type: #ryft::DifferentiableOperation<__DifferentiationContext>);
            predicate
        }));
        // Higher-order payload rules (condition/while/scan) forward-differentiate and linearize their nested
        // programs through the call-scoped `DifferentiationDriver`, whose implementations carry the direct
        // `Program::jvp`/`Program::linearize` bounds at their construction sites, so the dispatcher itself only
        // supplies the `From<ZeroOperation>` conversion those rules stage structural zeros through.
        where_clause.predicates.push(syn::parse_quote! {
            #differentiation_self_type: ::std::convert::From<#ryft::ZeroOperation<#primary_type>>
        });

        let jvp_arms = variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let operation_type = &variant.program_payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#operation_type as #ryft::DifferentiableOperation<__DifferentiationContext>>::jvp(
                        #receiver,
                        context,
                        driver,
                        inputs,
                    )
                },
            }
        });
        let (differentiation_impl_generics, _, differentiation_where_clause) =
            differentiation_generics.split_for_impl();

        const_block(quote! {
            #[automatically_derived]
            impl #differentiation_impl_generics
                #ryft::DifferentiableOperation<__DifferentiationContext>
                for #differentiation_self_type
            #differentiation_where_clause
            {
                fn jvp<__D: #ryft::DifferentiationDriver<__DifferentiationContext>>(
                    &self,
                    context: &__DifferentiationContext,
                    driver: &__D,
                    inputs: &[#ryft::DifferentiationDual<
                        <__DifferentiationContext as #ryft::Domain>::Value,
                    >],
                ) -> ::std::result::Result<
                    ::std::vec::Vec<#ryft::DifferentiationDual<
                        <__DifferentiationContext as #ryft::Domain>::Value,
                    >>,
                    #ryft::DifferentiationError,
                > {
                    match self {
                        #(#jvp_arms)*
                    }
                }
            }
        })
    }

    /// Generates the `TransposableOperation` dispatcher. Single-value-parameter enums transpose over a separate
    /// generated `__TranspositionValue` parameter. Enums with two or more value parameters pin the transposition value
    /// to the first (tangent/cotangent) value parameter. Higher-order rules request nested-program transposition through
    /// their instruction-scoped driver, whose concrete implementation establishes the corresponding
    /// `Program::transpose_with_respect_to` bounds.
    fn generate_transposable_operation(&self) -> TokenStream {
        let variants = &self.variants;
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;

        let operation_self_type = &self.self_type;
        let program_constant_type = &self.program_constant_type;
        let has_separate_transposition_value_type = self.has_single_value_parameter;
        let transposed_value_type: syn::Type = if has_separate_transposition_value_type {
            syn::parse_quote!(__TranspositionValue)
        } else {
            syn::parse_quote!(#program_constant_type)
        };
        let mut transposition_generics = self.operation_generics.clone();
        if has_separate_transposition_value_type {
            transposition_generics.params.push(syn::parse_quote!(__TranspositionValue));
        }

        let where_clause = transposition_generics.make_where_clause();
        if has_separate_transposition_value_type {
            where_clause
                .predicates
                .push(syn::parse_quote!(#transposed_value_type: #ryft::Value<Type = #primary_type>));
            where_clause.predicates.extend(generic_parameter_bounds_as_predicates(
                &self.generics,
                program_constant_type,
                &transposed_value_type,
            ));
        }
        where_clause
            .predicates
            .push(syn::parse_quote!(#operation_self_type: #ryft::Operation<#primary_type>));
        where_clause.predicates.extend(variants.iter().map(|variant| {
            let operation_type = &variant.payload_type;
            let predicate: syn::WherePredicate = syn::parse_quote! {
                #operation_type: #ryft::TransposableOperation<
                    #transposed_value_type,
                    #operation_self_type,
                >
            };
            predicate
        }));

        let (transposition_impl_generics, _, transposition_where_clause) = transposition_generics.split_for_impl();
        let transpose_arms = variants.iter().map(|variant| {
            let variant_ident = &variant.ident;
            let operation_type = &variant.payload_type;
            let receiver = variant.receiver();
            quote! {
                Self::#variant_ident(operation) => {
                    <#operation_type as #ryft::TransposableOperation<
                        #transposed_value_type,
                        #operation_self_type,
                    >>::transpose(#receiver, context, driver, inputs, outputs)
                },
            }
        });

        const_block(quote! {
            #[automatically_derived]
            impl #transposition_impl_generics
                #ryft::TransposableOperation<#transposed_value_type, #operation_self_type>
                for #operation_self_type
            #transposition_where_clause
            {
                fn transpose<__D: #ryft::TranspositionDriver<
                    #transposed_value_type,
                    #operation_self_type,
                >>(
                    &self,
                    context: &mut #ryft::TracingContext<
                        #transposed_value_type,
                        #operation_self_type,
                    >,
                    driver: &__D,
                    inputs: &[#ryft::partial::PartialValue<
                        #ryft::Tracer<#ryft::TracingContext<
                            #transposed_value_type,
                            #operation_self_type,
                        >>,
                    >],
                    outputs: &[#ryft::MaybeZero<
                        #ryft::Tracer<#ryft::TracingContext<
                            #transposed_value_type,
                            #operation_self_type,
                        >>,
                    >],
                ) -> ::std::result::Result<
                    ::std::vec::Vec<#ryft::MaybeZero<
                        #ryft::Tracer<#ryft::TracingContext<
                            #transposed_value_type,
                            #operation_self_type,
                        >>,
                    >>,
                    #ryft::DifferentiationError,
                > {
                    match self {
                        #(#transpose_arms)*
                    }
                }
            }
        })
    }

    /// Generates the `From<Payload>` and borrowed `TryFrom<&Enum>` conversion implementations for one
    /// conversion-enabled variant. Boxed payloads box the payload in `From` and deref through the box in `TryFrom`.
    ///
    fn generate_conversion_impl(&self, variant: &OperationVariant) -> TokenStream {
        let generics = &self.conversion_generics;
        let enum_ident = &self.ident;
        let enum_type = &self.self_type;
        let (impl_generics, _, where_clause) = generics.split_for_impl();
        let variant_ident = &variant.ident;
        let operation_type = &variant.payload_type;
        let mut try_from_generics = generics.clone();
        try_from_generics
            .params
            .insert(0, syn::GenericParam::Lifetime(syn::LifetimeParam::new(syn::parse_quote!('__operation))));
        let (try_from_impl_generics, _, try_from_where_clause) = try_from_generics.split_for_impl();

        let from_body = if variant.is_boxed {
            quote!(Self::#variant_ident(::std::boxed::Box::new(operation)))
        } else {
            quote!(Self::#variant_ident(operation))
        };
        let try_from_body = if variant.is_boxed { quote!(Ok(&**operation)) } else { quote!(Ok(operation)) };

        quote! {
            #[automatically_derived]
            impl #impl_generics ::std::convert::From<#operation_type> for #enum_type
            #where_clause
            {
                fn from(operation: #operation_type) -> Self {
                    #from_body
                }
            }

            #[automatically_derived]
            impl #try_from_impl_generics ::std::convert::TryFrom<&'__operation #enum_type>
                for &'__operation #operation_type
            #try_from_where_clause
            {
                type Error = ();

                fn try_from(value: &'__operation #enum_type) -> ::std::result::Result<Self, ()> {
                    match value {
                        #enum_ident::#variant_ident(operation) => #try_from_body,
                        _ => Err(()),
                    }
                }
            }
        }
    }
    /// Builds the generics for the generated [`InterpretableOperation`] dispatcher: the enum generics with
    /// program-shaped value substitutions applied, one generated `__Context` parameter, the context's [`Domain`]
    /// equalities, the constant-lifting `Constant` context bound, and one `InterpretableOperation` predicate per
    /// payload.
    fn interpretation_generics(&self) -> syn::Generics {
        let ryft = &self.ryft_crate;
        let primary_type = &self.operation_type;
        let program_constant_type = &self.program_constant_type;
        let has_separate_interpretation_value_type = self.has_single_value_parameter;
        let interpretation_value_type: syn::Type = syn::parse_quote!(<__Context as #ryft::Domain>::Value);
        let mut generics = self.program_generics.clone();
        generics.params.push(syn::parse_quote!(__Context));
        let where_clause = generics.make_where_clause();
        let mut domain_bound: syn::TypeParamBound = syn::parse_quote!(#ryft::Domain<Type = #primary_type>);
        if !has_separate_interpretation_value_type {
            domain_bound = syn::parse_quote! {
                #ryft::Domain<
                    Type = #primary_type,
                    Value = #program_constant_type,
                >
            };
        }
        where_clause.predicates.push(syn::parse_quote!(__Context: #domain_bound));
        if has_separate_interpretation_value_type {
            where_clause.predicates.extend(generic_parameter_bounds_as_predicates(
                &self.generics,
                program_constant_type,
                &interpretation_value_type,
            ));
            where_clause.predicates.push(syn::parse_quote! {
                __Context: #ryft::Constant<
                    #interpretation_value_type,
                    #program_constant_type,
                >
            });
        }
        where_clause.predicates.extend(self.variants.iter().map(|variant| {
            let operation_type = &variant.program_payload_type;
            let predicate: syn::WherePredicate = syn::parse_quote! {
                #operation_type: #ryft::InterpretableOperation<__Context>
            };
            predicate
        }));
        generics
    }
}

/// Operation enum variant extracted from the derive input, together with the payload metadata that drives the
/// generated dispatch arms, predicates, and conversions.
struct OperationVariant {
    /// Identifier of the enum variant.
    ident: syn::Ident,

    /// Operation type exposed by generated conversions.
    payload_type: syn::Type,

    /// Operation type used by generated program-shaped semantic implementations.
    program_payload_type: syn::Type,

    /// Whether the stored payload is `Box<operation_type>`.
    is_boxed: bool,

    /// Whether this variant stores a bare generic extension payload.
    is_generic_extension: bool,
}

impl OperationVariant {
    /// Receiver expression to use when delegating to the wrapped operation.
    fn receiver(&self) -> TokenStream {
        if self.is_boxed { quote!(&**operation) } else { quote!(operation) }
    }
}

/// Builds the generics used by the generated [`Operation`] and [`Display`] implementations: the enum generics
/// without defaults, plus one `Payload: Operation<T>` predicate per bare generic payload (concrete payloads already
/// implement [`Operation`] on their own).
fn operation_generics(
    generics: &syn::Generics,
    variants: &[OperationVariant],
    ryft: &syn::Path,
    operation_type: &syn::Type,
) -> syn::Generics {
    let mut generics = generics.without_defaults();
    let generic_operation_bounds = variants.iter().filter(|variant| variant.is_generic_extension).map(|variant| {
        let payload_type = &variant.payload_type;
        let predicate: syn::WherePredicate = syn::parse_quote!(#payload_type: #ryft::Operation<#operation_type>);
        predicate
    });
    generics.make_where_clause().predicates.extend(generic_operation_bounds);
    generics
}

/// Returns the inner type of a `Box<T>` type expression. This recognizes any type-path whose final path segment is
/// `Box` with exactly one type argument and returns that type argument, returning [`None`] for any other type.
fn boxed_inner_type(ty: &syn::Type) -> Option<syn::Type> {
    let syn::Type::Path(type_path) = ty else {
        return None;
    };
    if type_path.qself.is_some() {
        return None;
    }
    let segment = type_path.path.segments.last()?;
    if segment.ident != "Box" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return None;
    };
    if arguments.args.len() != 1 {
        return None;
    }
    match arguments.args.first() {
        Some(syn::GenericArgument::Type(inner_type)) => Some(inner_type.clone()),
        _ => None,
    }
}

/// Returns whether `ty` is exactly a bare enum type parameter (e.g., the `Extension` payload of an
/// `Extension(Extension)` variant). Bare generic payloads are the ones whose generated conversions must be skipped,
/// because a `From<Extension>` implementation would overlap with the concrete payload conversions whenever
/// `Extension` is instantiated as one of the concrete payload types.
fn is_bare_generic_parameter(ty: &syn::Type, generics: &syn::Generics) -> bool {
    let syn::Type::Path(type_path) = ty else {
        return false;
    };
    if type_path.qself.is_some() || type_path.path.segments.len() != 1 {
        return false;
    }
    let Some(segment) = type_path.path.segments.first() else {
        return false;
    };
    if !matches!(segment.arguments, syn::PathArguments::None) {
        return false;
    }
    generics.type_params().any(|parameter| parameter.ident == segment.ident)
}

/// Returns whether `ty` is exactly the provided identifier.
fn type_is_ident(ty: &syn::Type, ident: &syn::Ident) -> bool {
    matches!(ty, syn::Type::Path(syn::TypePath { qself: None, path }) if path.is_ident(ident))
}

/// Returns whether `ty` mentions the provided identifier anywhere in its structure (as a bare path segment or nested
/// inside array, function, group, parenthesized, pointer, reference, slice, tuple, or generic-argument positions).
fn type_mentions_ident(ty: &syn::Type, ident: &syn::Ident) -> bool {
    match ty {
        syn::Type::Array(ty) => type_mentions_ident(&ty.elem, ident),
        syn::Type::BareFn(ty) => {
            ty.inputs.iter().any(|input| type_mentions_ident(&input.ty, ident))
                || match &ty.output {
                    syn::ReturnType::Default => false,
                    syn::ReturnType::Type(_, ty) => type_mentions_ident(ty, ident),
                }
        }
        syn::Type::Group(ty) => type_mentions_ident(&ty.elem, ident),
        syn::Type::Paren(ty) => type_mentions_ident(&ty.elem, ident),
        syn::Type::Path(ty) => {
            ty.qself.as_ref().is_some_and(|qself| type_mentions_ident(&qself.ty, ident))
                || ty.path.segments.iter().any(|segment| {
                    segment.ident == *ident
                        || match &segment.arguments {
                            syn::PathArguments::None => false,
                            syn::PathArguments::AngleBracketed(arguments) => arguments.args.iter().any(|argument| {
                                matches!(
                                    argument,
                                    syn::GenericArgument::Type(ty) if type_mentions_ident(ty, ident)
                                ) || matches!(
                                    argument,
                                    syn::GenericArgument::AssocType(argument)
                                        if type_mentions_ident(&argument.ty, ident)
                                )
                            }),
                            syn::PathArguments::Parenthesized(arguments) => {
                                arguments.inputs.iter().any(|ty| type_mentions_ident(ty, ident))
                                    || match &arguments.output {
                                        syn::ReturnType::Default => false,
                                        syn::ReturnType::Type(_, ty) => type_mentions_ident(ty, ident),
                                    }
                            }
                        }
                })
        }
        syn::Type::Ptr(ty) => type_mentions_ident(&ty.elem, ident),
        syn::Type::Reference(ty) => type_mentions_ident(&ty.elem, ident),
        syn::Type::Slice(ty) => type_mentions_ident(&ty.elem, ident),
        syn::Type::Tuple(ty) => ty.elems.iter().any(|ty| type_mentions_ident(ty, ident)),
        _ => false,
    }
}

/// Substitutes bare type identifiers in `ty` according to the provided substitutions, returning the substituted
/// type. Refer to the documentation of [`TypeIdentSubstituter`] for information on which mentions are substituted.
fn substitute_type_idents(ty: &syn::Type, substitutions: &[(syn::Ident, syn::Type)]) -> syn::Type {
    let mut ty = ty.clone();
    TypeIdentSubstituter { substitutions }.visit_type_mut(&mut ty);
    ty
}

/// Substitutes bare type identifiers in `generics` according to the provided substitutions and removes the
/// substituted type parameters from the parameter list (they are replaced by concrete types and must not remain
/// generic in the generated implementations).
fn substitute_generics(generics: &syn::Generics, substitutions: &[(syn::Ident, syn::Type)]) -> syn::Generics {
    let mut generics = generics.clone();
    generics.params = generics
        .params
        .into_iter()
        .filter(|parameter| {
            !matches!(
                parameter,
                syn::GenericParam::Type(parameter)
                    if substitutions.iter().any(|(ident, _)| parameter.ident == *ident)
            )
        })
        .collect();
    TypeIdentSubstituter { substitutions }.visit_generics_mut(&mut generics);
    generics
}

/// Copies the declared bounds of the `source` generic parameter (both inline bounds and where-clause predicates
/// mentioning it) onto the generated `target` type, so that a generated value parameter inherits the same
/// capability requirements that the enum declares for its own value parameter.
///
/// # Parameters
///
///   * `generics` - Enum generics declaring the `source` parameter.
///   * `source` - Enum value parameter whose bounds are copied.
///   * `target` - Generated type that receives the copied bounds.
fn generic_parameter_bounds_as_predicates(
    generics: &syn::Generics,
    source: &syn::Ident,
    target: &syn::Type,
) -> Vec<syn::WherePredicate> {
    let mut predicates = generics
        .type_params()
        .find(|parameter| parameter.ident == *source)
        .into_iter()
        .flat_map(|parameter| parameter.bounds.iter())
        .map(|bound| syn::parse_quote!(#target: #bound))
        .collect::<Vec<syn::WherePredicate>>();
    if let Some(where_clause) = &generics.where_clause {
        predicates.extend(where_clause.predicates.iter().filter_map(|predicate| match predicate {
            syn::WherePredicate::Type(predicate) if type_mentions_ident(&predicate.bounded_ty, source) => {
                let mut predicate = syn::WherePredicate::Type(predicate.clone());
                TypeIdentSubstituter { substitutions: &[(source.clone(), target.clone())] }
                    .visit_where_predicate_mut(&mut predicate);
                Some(predicate)
            }
            _ => None,
        }));
    }
    predicates
}

/// [`VisitMut`] visitor that replaces bare type identifier mentions with concrete replacement types: a
/// single-segment argument-free path is replaced wholesale, while a multi-segment path whose first segment matches a
/// substituted identifier has that first segment replaced by the replacement path (preserving the remaining
/// segments), so that associated-type projections through a substituted parameter keep working.
struct TypeIdentSubstituter<'a> {
    /// Type identifier substitutions.
    substitutions: &'a [(syn::Ident, syn::Type)],
}

impl VisitMut for TypeIdentSubstituter<'_> {
    fn visit_type_mut(&mut self, ty: &mut syn::Type) {
        if let syn::Type::Path(type_path) = ty
            && type_path.qself.is_none()
        {
            if type_path.path.segments.len() == 1
                && let Some(segment) = type_path.path.segments.first()
                && matches!(segment.arguments, syn::PathArguments::None)
                && let Some((_, replacement)) = self.substitutions.iter().find(|(ident, _)| segment.ident == *ident)
            {
                *ty = replacement.clone();
                return;
            }
            if let Some(first_segment) = type_path.path.segments.first()
                && matches!(first_segment.arguments, syn::PathArguments::None)
                && let Some((_, syn::Type::Path(replacement))) =
                    self.substitutions.iter().find(|(ident, _)| first_segment.ident == *ident)
                && replacement.qself.is_none()
            {
                let remaining_segments = type_path.path.segments.iter().skip(1).cloned();
                type_path.path.leading_colon = replacement.path.leading_colon;
                type_path.path.segments = replacement.path.segments.iter().cloned().chain(remaining_segments).collect();
            }
        }
        syn::visit_mut::visit_type_mut(self, ty);
    }
}

/// Builds the program-shaped value substitutions for the provided value type parameters: every value parameter
/// after the first two is substituted with the program constant type (the first value parameter). The first value
/// parameter is the program-constant/flowing value space and the second is the capture/constant space, while later
/// value parameters are payload-specific metadata that program-shaped implementations (which have one value space)
/// must pin to the program constant type. Refer to the documentation of the [`Operation`] trait for information on
/// how the value types of generated implementations are inferred.
fn program_value_substitutions(
    value_type_parameters: &[syn::Ident],
    program_constant_type: &syn::Ident,
) -> Vec<(syn::Ident, syn::Type)> {
    value_type_parameters
        .iter()
        .skip(2)
        .cloned()
        .map(|parameter| {
            let replacement: syn::Type = syn::parse_quote!(#program_constant_type);
            (parameter, replacement)
        })
        .collect()
}

/// Returns generic value parameters bounded by `Value<Type = operation_type>`.
fn value_type_parameters(generics: &syn::Generics, operation_type: &syn::Type) -> Vec<syn::Ident> {
    generics
        .type_params()
        .filter(|parameter| {
            parameter.bounds.iter().any(|bound| {
                value_bound_argument(bound).is_some_and(|argument| type_tokens_equal(&argument, operation_type))
            }) || generics.where_clause.iter().any(|where_clause| {
                where_clause.predicates.iter().any(|predicate| match predicate {
                    syn::WherePredicate::Type(predicate) if type_is_ident(&predicate.bounded_ty, &parameter.ident) => {
                        predicate.bounds.iter().any(|bound| {
                            value_bound_argument(bound)
                                .is_some_and(|argument| type_tokens_equal(&argument, operation_type))
                        })
                    }
                    _ => false,
                })
            })
        })
        .map(|parameter| parameter.ident.clone())
        .collect()
}

/// Returns whether two types have the same token representation. Given that procedural macros are executed before
/// type checking and inference is performed by the Rust compiler, token equality is the strongest type equality we
/// can check for here (e.g., type aliases cannot be resolved).
fn type_tokens_equal(left: &syn::Type, right: &syn::Type) -> bool {
    left.to_token_stream().to_string().replace(' ', "") == right.to_token_stream().to_string().replace(' ', "")
}

/// Extracts distinct `Value<Type = T>` bound arguments from `generics`, preserving their first-seen order.
fn unique_value_bound_arguments(generics: &syn::Generics) -> Vec<syn::Type> {
    value_bound_arguments(generics).into_iter().fold(Vec::new(), |mut arguments, argument| {
        if arguments.iter().all(|existing_argument| !type_tokens_equal(existing_argument, &argument)) {
            arguments.push(argument);
        }
        arguments
    })
}

/// Extracts all `Value<Type = T>` bound arguments from `generics`.
fn value_bound_arguments(generics: &syn::Generics) -> Vec<syn::Type> {
    let parameter_bounds = generics.type_params().flat_map(|parameter| parameter.bounds.iter());
    let where_bounds = generics
        .where_clause
        .iter()
        .flat_map(|where_clause| where_clause.predicates.iter())
        .filter_map(|predicate| match predicate {
            syn::WherePredicate::Type(predicate) => Some(predicate.bounds.iter()),
            _ => None,
        })
        .flatten();

    parameter_bounds.chain(where_bounds).filter_map(value_bound_argument).collect()
}

/// Returns the bound `Type` from a `Value<Type = T>` trait bound.
fn value_bound_argument(bound: &syn::TypeParamBound) -> Option<syn::Type> {
    let syn::TypeParamBound::Trait(bound) = bound else {
        return None;
    };
    let segment = bound.path.segments.last()?;
    if segment.ident != "Value" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return None;
    };
    match arguments.args.first() {
        Some(syn::GenericArgument::AssocType(binding)) if arguments.args.len() == 1 && binding.ident == "Type" => {
            Some(binding.ty.clone())
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use quote::{ToTokens, quote};

    use super::*;

    /// Parses a derive input and extracts its operation attributes.
    fn extract_attributes(tokens: TokenStream) -> OperationParser {
        let input = syn::parse2(tokens).expect("failed to parse derive input");
        let mut parser = OperationParser::new();
        parser.extract_attributes(&input);
        parser
    }

    #[test]
    fn test_operation_parser_add_error_and_compile_error() {
        let mut parser = OperationParser::new();
        parser.add_error(quote!(variant_a), "first error");
        parser.add_error(quote!(variant_b), "second error");
        assert!(parser.has_errors());
        let error = parser.into_compile_error().to_string();
        assert!(error.contains("compile_error"));
        assert!(error.contains("first error"));
        assert!(error.contains("second error"));
    }

    #[test]
    fn test_operation_parser_extract_attributes() {
        let generator = extract_attributes(quote! {
            #[ryft(crate = "wrapped::ryft")]
            #[ryft(dispatch(batching, differentiation, transposition))]
            enum Operation<V: Value<Type = DataType>> {
                Zero(ZeroOperation<DataType>),
            }
        });
        assert!(generator.errors.is_empty());
        assert_eq!(generator.ryft_crate.to_token_stream().to_string(), "wrapped :: ryft");
        assert_eq!(generator.operation_type.as_ref().unwrap().to_token_stream().to_string(), "DataType");
        let dispatchers = generator.dispatchers.unwrap_or_default();
        assert!(dispatchers.batching);
        assert!(dispatchers.differentiation);
        assert!(dispatchers.transposition);

        let generator = extract_attributes(quote! {
            enum Operation<V: Value<Type = DataType>> {
                Zero(ZeroOperation<DataType>),
            }
        });
        assert!(generator.errors.is_empty());
        let dispatchers = generator.dispatchers.unwrap_or_default();
        assert!(!dispatchers.batching);
        assert!(!dispatchers.differentiation);
        assert!(!dispatchers.transposition);
    }

    #[test]
    fn test_operation_parser_extract_dispatchers() {
        for (dispatcher, batching, differentiation, transposition) in [
            (quote!(batching), true, false, false),
            (quote!(differentiation), false, true, false),
            (quote!(transposition), false, false, true),
        ] {
            let generator = extract_attributes(quote! {
                #[ryft(dispatch(#dispatcher))]
                enum Operation<V: Value<Type = DataType>> {
                    Zero(ZeroOperation<DataType>),
                }
            });
            assert!(generator.errors.is_empty());
            let dispatchers = generator.dispatchers.unwrap_or_default();
            assert_eq!(dispatchers.batching, batching);
            assert_eq!(dispatchers.differentiation, differentiation);
            assert_eq!(dispatchers.transposition, transposition);
        }
    }

    #[test]
    fn test_operation_parser_rejects_invalid_attributes() {
        let cases = [
            (quote!(#[ryft(crate = "ryft", unknown = "value")]), "invalid '#[ryft(...)]' attribute: 'unknown'"),
            (quote!(#[ryft(dispatch())]), "must select at least one dispatcher"),
            (quote!(#[ryft(dispatch(lowering))]), "invalid '#[ryft(dispatch(...))]' dispatcher: 'lowering'"),
            (quote!(#[ryft(dispatch(batching, batching))]), "duplicate ryft dispatcher 'batching'"),
            (
                quote!(#[ryft(dispatch(batching))] #[ryft(dispatch(transposition))]),
                "duplicate ryft attribute 'dispatch(...)'",
            ),
        ];
        for (attributes, expected_error) in cases {
            let generator = extract_attributes(quote! {
                #attributes
                enum Operation<V: Value<Type = DataType>> {
                    Zero(ZeroOperation<DataType>),
                }
            });
            let errors = generator.errors.iter().map(syn::Error::to_string).collect::<Vec<_>>();
            assert!(errors.iter().any(|error| error.contains(expected_error)), "errors: {errors:?}");
        }
    }

    #[test]
    fn test_operation_parser_extract_variants() {
        let mut generator = OperationParser::new();
        let mut input = syn::parse2(quote! {
            enum Operation<V: Value<Type = DataType>, Extension> {
                Zero(ZeroOperation<DataType>),
                Boxed(Box<CustomJvpOperation<DataType, V>>),
                Recursive(WhileOperation<DataType, V, Self>),
                Extension(Extension),
            }
        })
        .expect("failed to parse derive input");
        // `Self` mentions must be replaced with their fully-qualified path first, exactly like the derive entry
        // points do.
        replace_self_type(&mut input);
        let variants = generator.extract_variants(&input);
        assert!(generator.errors.is_empty());
        assert_eq!(variants.len(), 4);
        assert!(!variants[0].is_boxed && !variants[0].is_generic_extension);
        assert!(variants[1].is_boxed && !variants[1].is_generic_extension);
        assert!(!variants[2].is_boxed && !variants[2].is_generic_extension);
        assert!(!variants[3].is_boxed && variants[3].is_generic_extension);

        // Non-enum inputs and variants that are not single-payload tuple variants are rejected.
        let mut generator = OperationParser::new();
        let input = syn::parse2(quote! {
            struct Operation<V: Value<Type = DataType>> {
                value: V,
            }
        })
        .expect("failed to parse derive input");
        assert!(generator.extract_variants(&input).is_empty());
        assert_eq!(generator.errors.len(), 1);

        let mut generator = OperationParser::new();
        let input = syn::parse2(quote! {
            enum Operation<V: Value<Type = DataType>> {
                Unit,
                Named { operation: ZeroOperation<DataType> },
            }
        })
        .expect("failed to parse derive input");
        assert!(generator.extract_variants(&input).is_empty());
        assert_eq!(generator.errors.len(), 2);

        let mut generator = OperationParser::new();
        let input = syn::parse2(quote! {
            enum Operation<V: Value<Type = DataType>> {
                #[ryft(unsupported)]
                Zero(#[ryft(unsupported)] ZeroOperation<DataType>),
            }
        })
        .expect("failed to parse derive input");
        assert_eq!(generator.extract_variants(&input).len(), 1);
        assert_eq!(generator.errors.len(), 2);
        assert!(generator.errors.iter().all(|error| error.to_string() == NESTED_ATTRIBUTE_ERROR));
    }

    #[test]
    fn test_operation_parser_normalizes_operation_enum() {
        let mut input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<V, C, Extension, F = V>
            where
                V: Value<Type = DataType>,
                C: Value<Type = DataType>,
                F: Value<Type = DataType>,
            {
                Recursive(Box<WhileOperation<DataType, F, Self>>),
                Extension(Extension),
            }
        };
        replace_self_type(&mut input);

        let mut parser = OperationParser::new();
        parser.extract_attributes(&input);
        let operation = parser.normalize_input(&input).expect("failed to normalize operation enum");

        assert_eq!(operation.operation_type.to_token_stream().to_string(), "DataType");
        assert_eq!(operation.program_constant_type, "V");
        assert!(!operation.has_single_value_parameter);
        assert!(!operation.program_generics.type_params().any(|parameter| parameter.ident == "F"));
        assert!(
            operation
                .program_self_type
                .to_token_stream()
                .to_string()
                .contains("Operation < V , C , Extension , V >")
        );
        assert!(operation.variants[0].is_boxed);
        assert!(
            operation.variants[0]
                .program_payload_type
                .to_token_stream()
                .to_string()
                .contains("WhileOperation < DataType , V"),
        );
        assert!(operation.variants[1].is_generic_extension);
    }

    #[test]
    fn test_boxed_inner_type() {
        let inner = boxed_inner_type(&syn::parse_quote!(Box<CustomJvpOperation<T, V>>)).unwrap();
        assert_eq!(inner.to_token_stream().to_string().replace(' ', ""), "CustomJvpOperation<T,V>");
        assert!(boxed_inner_type(&syn::parse_quote!(CustomJvpOperation<T, V>)).is_none());
    }

    #[test]
    fn test_is_bare_generic_parameter() {
        let input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<T, Extension> {
                Extension(Extension),
            }
        };
        assert!(is_bare_generic_parameter(&syn::parse_quote!(Extension), &input.generics));
        assert!(!is_bare_generic_parameter(&syn::parse_quote!(Box<Extension>), &input.generics));
        assert!(!is_bare_generic_parameter(&syn::parse_quote!(Other), &input.generics));
    }

    #[test]
    fn test_program_value_substitutions() {
        let value: syn::Ident = syn::parse_quote!(V);
        assert!(program_value_substitutions(std::slice::from_ref(&value), &value).is_empty());
        assert!(program_value_substitutions(&[value.clone(), syn::parse_quote!(C)], &value).is_empty());

        let substitutions = program_value_substitutions(
            &[value.clone(), syn::parse_quote!(C), syn::parse_quote!(F), syn::parse_quote!(P)],
            &value,
        );
        assert_eq!(substitutions.len(), 2);
        assert_eq!(substitutions[0].0, "F");
        assert!(type_tokens_equal(&substitutions[0].1, &syn::parse_quote!(V)));
        assert_eq!(substitutions[1].0, "P");
        assert!(type_tokens_equal(&substitutions[1].1, &syn::parse_quote!(V)));
    }

    #[test]
    fn test_substitute_type_idents() {
        let r#type: syn::Type = syn::parse_quote!((F, Wrapper<F>, F::Item, fn(F) -> Other));
        let substituted = substitute_type_idents(&r#type, &[(syn::parse_quote!(F), syn::parse_quote!(V))]);
        let expected: syn::Type = syn::parse_quote!((V, Wrapper<V>, V::Item, fn(V) -> Other));
        assert!(type_tokens_equal(&substituted, &expected));
    }

    #[test]
    fn test_substitute_generics() {
        let input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<V, F: Trait<V>, X = F>
            where
                Wrapper<F>: Bound,
                F::Item: Other
            {}
        };
        let expected: syn::DeriveInput = syn::parse_quote! {
            enum Operation<V, X = V>
            where
                Wrapper<V>: Bound,
                V::Item: Other
            {}
        };
        let substituted = substitute_generics(&input.generics, &[(syn::parse_quote!(F), syn::parse_quote!(V))]);
        assert_eq!(
            substituted.to_token_stream().to_string().replace(' ', ""),
            expected.generics.to_token_stream().to_string().replace(' ', ""),
        );
    }

    #[test]
    fn test_generic_parameter_bounds_as_predicates() {
        let input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<V: Value<Type = ArrayType> + Clone, U>
            where
                Wrapper<V>: Bound,
                U: Unrelated
            {}
        };
        let predicates = generic_parameter_bounds_as_predicates(
            &input.generics,
            &syn::parse_quote!(V),
            &syn::parse_quote!(RuntimeValue),
        )
        .into_iter()
        .map(|predicate| predicate.to_token_stream().to_string().replace(' ', ""))
        .collect::<Vec<_>>();

        assert!(predicates.contains(&"RuntimeValue:Value<Type=ArrayType>".to_string()));
        assert!(predicates.contains(&"RuntimeValue:Clone".to_string()));
        assert!(predicates.contains(&"Wrapper<RuntimeValue>:Bound".to_string()));
        assert!(predicates.iter().all(|predicate| !predicate.contains("Unrelated")));
    }

    #[test]
    fn test_value_bound_arguments() {
        let input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<T, V: Value<Type = T>, W>
            where
                W: Value<Type = DataType>,
            {}
        };
        let arguments = value_bound_arguments(&input.generics);
        assert_eq!(arguments.len(), 2);
        assert_eq!(arguments[0].to_token_stream().to_string(), "T");
        assert_eq!(arguments[1].to_token_stream().to_string(), "DataType");
    }

    #[test]
    fn test_unique_value_bound_arguments() {
        let input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<V: Value<Type = ArrayType>, C, F>
            where
                C: Value<Type = ArrayType>,
                F: Value<Type = DataType>,
            {}
        };
        let arguments = unique_value_bound_arguments(&input.generics);
        assert_eq!(arguments.len(), 2);
        assert_eq!(arguments[0].to_token_stream().to_string(), "ArrayType");
        assert_eq!(arguments[1].to_token_stream().to_string(), "DataType");
    }

    #[test]
    fn test_value_type_parameters() {
        let input: syn::DeriveInput = syn::parse_quote! {
            enum Operation<V: Value<Type = ArrayType>, C, F>
            where
                C: Value<Type = ArrayType>,
                F: Value<Type = DataType>,
            {}
        };
        let parameters = value_type_parameters(&input.generics, &syn::parse_quote!(ArrayType));
        assert_eq!(parameters.len(), 2);
        assert_eq!(parameters[0].to_string(), "V");
        assert_eq!(parameters[1].to_string(), "C");
    }
}
