[package]
name = "ryft-xla"
version = "0.0.3"
readme = "README.md"
description = "XLA backend for the Ryft library."
keywords = ["ryft", "xla", "pjrt", "gpu", "tpu"]
include = [
    "src/**/*",
    "Cargo.toml",
    "CHANGELOG.md",
    "README.md",
    "../../LICENSE-APACHE",
    "../../LICENSE-MIT",
    "../../NOTICE",
]

authors.workspace = true
edition.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true

[package.metadata.release]
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}", min = 1 },
    { file = "CHANGELOG.md", search = "Release Date", replace = "{{date}}", min = 1 },
    { file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n## [Unreleased] - Release Date\n", exactly = 1 },
]

[dependencies]
ryft-core.workspace = true
ryft-macros.workspace = true
ryft-mlir.workspace = true
ryft-pjrt.workspace = true
ryft-xla-sys.workspace = true
half.workspace = true
ndarray = { workspace = true, optional = true }
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
indoc.workspace = true
num-complex.workspace = true
pretty_assertions.workspace = true
tempfile.workspace = true

[features]
default = []
program-statistics = []
performance-benchmarking = []
ndarray = ["dep:ndarray"]
cuda-12 = ["ryft-pjrt/cuda-12"]
cuda-13 = ["ryft-pjrt/cuda-13"]
rocm-7 = ["ryft-pjrt/rocm-7"]
tpu = ["ryft-pjrt/tpu"]
neuron = ["ryft-pjrt/neuron"]
metal = ["ryft-pjrt/metal"]
mps = ["ryft-pjrt/mps"]

[[bin]]
name = "program_statistics"
path = "src/bin/program_statistics.rs"
required-features = ["program-statistics"]

[[bin]]
name = "compilation_benchmark"
path = "src/bin/compilation_benchmark.rs"
required-features = ["performance-benchmarking"]
